insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (253, 22, '6:29', '21:10', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (254, 74, '6:29', '21:08', 'Proin at turpis a pede posuere nonummy.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (255, 96, '6:18', '21:18', 'Aliquam erat volutpat.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (256, 59, '6:26', '21:23', 'Nullam porttitor lacus at turpis.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (257, 75, '6:16', '21:15', 'Sed ante.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (258, 20, '6:13', '21:13', 'Donec ut dolor.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (259, 49, '6:28', '21:15', 'Proin risus.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (260, 17, '6:15', '21:28', 'Nulla tempus.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (261, 76, '6:02', '21:25', 'Nulla nisl.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (262, 95, '6:12', '21:12', 'Praesent blandit lacinia erat.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (263, 47, '6:29', '21:00', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (264, 24, '6:11', '21:27', 'Donec ut mauris eget massa tempor convallis.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (265, 87, '6:20', '21:17', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (266, 84, '6:17', '21:18', 'Duis consequat dui nec nisi volutpat eleifend.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (267, 64, '6:00', '21:18', 'Aliquam erat volutpat.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (268, 53, '6:21', '21:25', 'Etiam faucibus cursus urna.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (269, 75, '6:00', '21:20', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (270, 65, '6:29', '21:24', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (271, 17, '6:05', '21:09', 'Sed vel enim sit amet nunc viverra dapibus.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (272, 31, '6:17', '21:25', 'Vestibulum sed magna at nunc commodo placerat.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (273, 100, '6:10', '21:18', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (274, 93, '6:15', '21:29', 'Duis aliquam convallis nunc.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (275, 26, '6:24', '21:01', 'Integer ac leo.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (276, 23, '6:13', '21:29', 'In hac habitasse platea dictumst.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (277, 69, '6:04', '21:27', 'Praesent blandit lacinia erat.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (278, 20, '6:21', '21:16', 'Nulla ac enim.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (279, 21, '6:04', '21:24', 'Mauris ullamcorper purus sit amet nulla.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (280, 11, '6:17', '21:05', 'Nulla facilisi.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (281, 97, '6:18', '21:12', 'In hac habitasse platea dictumst.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (282, 15, '6:16', '21:26', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (283, 81, '6:20', '21:19', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (284, 19, '6:02', '21:00', 'Praesent blandit.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (285, 31, '6:07', '21:29', 'Morbi non quam nec dui luctus rutrum.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (286, 70, '6:00', '21:25', 'Nulla nisl.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (287, 60, '6:29', '21:11', 'Vestibulum sed magna at nunc commodo placerat.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (288, 41, '6:28', '21:11', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (289, 66, '6:16', '21:06', 'Mauris ullamcorper purus sit amet nulla.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (290, 37, '6:12', '21:06', 'Sed accumsan felis.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (291, 45, '6:21', '21:21', 'Sed vel enim sit amet nunc viverra dapibus.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (292, 93, '6:05', '21:20', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (293, 24, '6:11', '21:22', 'Vestibulum sed magna at nunc commodo placerat.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (294, 39, '6:29', '21:10', 'Donec semper sapien a libero.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (295, 60, '6:11', '21:11', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (296, 63, '6:04', '21:04', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (297, 60, '6:10', '21:14', 'Sed accumsan felis.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (298, 46, '6:13', '21:25', 'Integer a nibh.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (299, 19, '6:16', '21:02', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (300, 17, '6:11', '21:26', 'Pellentesque ultrices mattis odio.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (301, 70, '6:08', '21:18', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (302, 24, '6:16', '21:11', 'Maecenas pulvinar lobortis est.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (303, 68, '6:11', '21:25', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (304, 91, '6:16', '21:19', 'Sed ante.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (305, 35, '6:18', '21:16', 'Nunc nisl.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (306, 87, '6:19', '21:03', 'Donec posuere metus vitae ipsum.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (307, 41, '6:20', '21:05', 'Nulla suscipit ligula in lacus.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (308, 40, '6:23', '21:22', 'Donec semper sapien a libero.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (309, 40, '6:28', '21:20', 'Aliquam non mauris.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (310, 55, '6:04', '21:03', 'Maecenas pulvinar lobortis est.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (311, 72, '6:14', '21:26', 'In hac habitasse platea dictumst.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (312, 84, '6:17', '21:05', 'Morbi a ipsum.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (313, 20, '6:00', '21:18', 'Etiam justo.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (314, 24, '6:04', '21:28', 'Vivamus in felis eu sapien cursus vestibulum.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (315, 23, '6:01', '21:29', 'Integer a nibh.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (316, 78, '6:29', '21:02', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (317, 32, '6:28', '21:15', 'Nulla ac enim.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (318, 53, '6:15', '21:27', 'Morbi ut odio.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (319, 93, '6:21', '21:04', 'Etiam pretium iaculis justo.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (320, 91, '6:03', '21:12', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (321, 40, '6:18', '21:14', 'Donec semper sapien a libero.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (322, 22, '6:22', '21:12', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (323, 62, '6:01', '21:16', 'Sed accumsan felis.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (324, 37, '6:13', '21:07', 'Nulla ac enim.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (325, 66, '6:03', '21:13', 'Duis consequat dui nec nisi volutpat eleifend.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (326, 88, '6:02', '21:21', 'Nunc rhoncus dui vel sem.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (327, 16, '6:25', '21:02', 'Donec semper sapien a libero.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (328, 56, '6:29', '21:29', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (329, 19, '6:03', '21:08', 'Nam nulla.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (330, 52, '6:00', '21:13', 'Donec dapibus.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (331, 40, '6:27', '21:02', 'Nulla ac enim.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (332, 96, '6:23', '21:20', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (333, 72, '6:10', '21:24', 'Cras pellentesque volutpat dui.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (334, 13, '6:09', '21:15', 'Pellentesque ultrices mattis odio.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (335, 25, '6:06', '21:09', 'Mauris ullamcorper purus sit amet nulla.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (336, 87, '6:17', '21:00', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (337, 68, '6:28', '21:06', 'Donec quis orci eget orci vehicula condimentum.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (338, 21, '6:21', '21:26', 'Morbi a ipsum.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (339, 19, '6:07', '21:23', 'Phasellus id sapien in sapien iaculis congue.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (340, 77, '6:20', '21:04', 'Donec dapibus.', 'Verde', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (341, 87, '6:01', '21:24', 'Nulla tellus.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (342, 73, '6:24', '21:19', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (343, 46, '6:22', '21:04', 'Nunc rhoncus dui vel sem.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (344, 94, '6:02', '21:12', 'Donec quis orci eget orci vehicula condimentum.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (345, 57, '6:04', '21:08', 'Integer tincidunt ante vel ipsum.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (346, 52, '6:05', '21:22', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (347, 68, '6:15', '21:18', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (348, 90, '6:01', '21:20', 'Curabitur at ipsum ac tellus semper interdum.', 'Verde', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (349, 65, '6:13', '21:20', 'Duis bibendum.', 'Verde', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (350, 72, '6:23', '21:12', 'Phasellus sit amet erat.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (351, 42, '6:15', '21:23', 'Aliquam non mauris.', 'Verde', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (352, 75, '6:10', '21:13', 'Aenean auctor gravida sem.', 'Verde', 5);
