insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (1, 290, 'Oba', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (2, 372, 'Babbleset', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (3, 301, 'Realfire', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (4, 265, 'Zooxo', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (5, 340, 'Wordware', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (6, 310, 'Babbleblab', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (7, 181, 'Jamia', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (8, 343, 'Cogibox', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (9, 161, 'Bubblemix', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (10, 381, 'Oyoloo', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (11, 316, 'Rhyloo', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (12, 177, 'Ntag', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (13, 223, 'Skalith', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (14, 326, 'Quamba', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (15, 352, 'Youspan', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (16, 138, 'Jabbercube', '1', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (17, 181, 'Buzzshare', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (18, 87, 'Kwimbee', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (19, 335, 'Mudo', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (20, 240, 'Mynte', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (21, 146, 'Eamia', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (22, 368, 'Kwideo', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (23, 278, 'Yodoo', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (24, 114, 'Flashset', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (25, 230, 'Eare', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (26, 258, 'Camido', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (27, 136, 'Quinu', '1', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (28, 74, 'Zoomlounge', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (29, 155, 'Meezzy', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (30, 356, 'Riffpath', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (31, 157, 'Trupe', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (32, 234, 'Shuffletag', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (33, 284, 'Skibox', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (34, 246, 'Buzzbean', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (35, 106, 'Demizz', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (36, 242, 'Skyble', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (37, 87, 'Wikizz', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (38, 164, 'Reallinks', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (39, 323, 'Devpoint', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (40, 342, 'Skynoodle', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (41, 215, 'Quaxo', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (42, 322, 'Edgetag', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (43, 157, 'Zoomcast', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (44, 309, 'Voonder', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (45, 335, 'Jazzy', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (46, 93, 'Muxo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (47, 236, 'Gabtune', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (48, 103, 'Tambee', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (49, 346, 'Twitternation', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (50, 329, 'Babbleopia', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (51, 364, 'Edgeclub', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (52, 299, 'Voonix', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (53, 111, 'Avamba', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (54, 96, 'Wikizz', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (55, 204, 'Aibox', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (56, 306, 'Aimbu', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (57, 248, 'Riffwire', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (58, 152, 'Meejo', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (59, 328, 'Dazzlesphere', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (60, 306, 'Kare', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (61, 393, 'Quimba', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (62, 104, 'Wikido', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (63, 174, 'Flashpoint', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (64, 337, 'Dynazzy', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (65, 288, 'Kazio', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (66, 317, 'Feedfish', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (67, 113, 'Devbug', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (68, 285, 'Gevee', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (69, 147, 'Pixonyx', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (70, 394, 'Linkbridge', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (71, 317, 'Vinder', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (72, 85, 'Thoughtworks', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (73, 76, 'Trudeo', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (74, 321, 'Eimbee', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (75, 140, 'Tambee', '1', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (76, 309, 'Vipe', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (77, 348, 'Buzzster', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (78, 350, 'Edgepulse', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (79, 85, 'Edgeify', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (80, 363, 'Riffpedia', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (81, 308, 'Buzzster', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (82, 376, 'Vimbo', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (83, 376, 'Kaymbo', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (84, 104, 'Npath', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (85, 400, 'Buzzster', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (86, 134, 'Voolith', '1', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (87, 308, 'Eire', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (88, 317, 'Skinte', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (89, 392, 'Aimbo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (90, 398, 'Realpoint', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (91, 126, 'Vinder', '1', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (92, 120, 'Gigabox', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (93, 244, 'Skimia', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (94, 273, 'Livetube', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (95, 255, 'Divanoodle', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (96, 96, 'Gigazoom', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (97, 241, 'Feedmix', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (98, 308, 'Topicblab', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (99, 97, 'Fiveclub', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (100, 133, 'Pixoboo', '1', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (101, 205, 'Voonte', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (102, 146, 'Browsebug', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (103, 352, 'Oyope', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (104, 127, 'Jabbercube', '1', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (105, 89, 'Avavee', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (106, 359, 'Chatterbridge', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (107, 393, 'Kazio', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (108, 156, 'Chatterpoint', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (109, 188, 'Realbridge', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (110, 75, 'Rooxo', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (111, 205, 'Bubblemix', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (112, 233, 'Youtags', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (113, 281, 'Browsetype', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (114, 400, 'Tagtune', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (115, 310, 'Wikizz', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (116, 328, 'Fadeo', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (117, 363, 'Gigashots', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (118, 173, 'Dabtype', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (119, 99, 'Plambee', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (120, 147, 'Jaxspan', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (121, 264, 'Mynte', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (122, 196, 'Babbleopia', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (123, 74, 'Skipstorm', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (124, 374, 'Twitterbeat', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (125, 301, 'Lazzy', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (126, 241, 'Janyx', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (127, 92, 'Topicshots', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (128, 214, 'Mita', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (129, 381, 'Shufflester', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (130, 370, 'Pixoboo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (131, 297, 'Vinte', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (132, 121, 'Kwimbee', '1', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (133, 137, 'Meevee', '1', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (134, 141, 'Meevee', '1', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (135, 268, 'Yombu', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (136, 325, 'Npath', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (137, 288, 'Agimba', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (138, 90, 'Blogtags', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (139, 340, 'Eadel', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (140, 191, 'Quinu', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (141, 321, 'Photospace', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (142, 82, 'Photolist', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (143, 214, 'Topicshots', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (144, 318, 'Minyx', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (145, 141, 'Thoughtworks', '1', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (146, 79, 'Buzzbean', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (147, 83, 'Lajo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (148, 239, 'Yacero', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (149, 82, 'Fiveclub', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (150, 70, 'Fadeo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (151, 279, 'Fanoodle', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (152, 307, 'Dabtype', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (153, 313, 'Twinte', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (154, 324, 'Shuffletag', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (155, 153, 'Abata', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (156, 340, 'Wordtune', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (157, 82, 'Jetpulse', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (158, 333, 'Linklinks', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (159, 258, 'Cogidoo', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (160, 159, 'Demimbu', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (161, 138, 'Gigashots', '1', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (162, 271, 'Zoomzone', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (163, 115, 'Mynte', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (164, 398, 'Mudo', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (165, 71, 'Feedbug', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (166, 210, 'Gabcube', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (167, 93, 'Topicblab', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (168, 370, 'Gigaclub', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (169, 162, 'Thoughtbridge', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (170, 133, 'Flashset', '1', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (171, 221, 'Meezzy', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (172, 119, 'Jatri', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (173, 124, 'Thoughtblab', '1', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (174, 215, 'Meevee', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (175, 365, 'Agimba', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (176, 290, 'Topicware', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (177, 357, 'Nlounge', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (178, 125, 'Zoomcast', '1', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (179, 350, 'Yodel', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (180, 152, 'Meetz', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (181, 186, 'Fanoodle', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (182, 287, 'Photobug', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (183, 206, 'Twitterwire', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (184, 89, 'Topiczoom', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (185, 302, 'Oodoo', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (186, 207, 'Thoughtbeat', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (187, 77, 'Dabjam', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (188, 376, 'Teklist', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (189, 253, 'Leexo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (190, 321, 'Skyvu', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (191, 144, 'Tagfeed', '1', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (192, 195, 'Oyonder', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (193, 330, 'Izio', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (194, 108, 'Wordtune', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (195, 303, 'Browsecat', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (196, 70, 'Cogilith', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (197, 337, 'Wordtune', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (198, 352, 'Wordware', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (199, 155, 'Snaptags', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (200, 250, 'Buzzshare', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (201, 282, 'Divanoodle', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (202, 381, 'Aimbo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (203, 392, 'Lazz', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (204, 338, 'Gigabox', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (205, 386, 'Ooba', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (206, 204, 'Skipfire', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (207, 88, 'Oyoloo', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (208, 170, 'Meevee', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (209, 156, 'Gabtune', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (210, 308, 'Trudoo', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (211, 333, 'Avaveo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (212, 338, 'Brightbean', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (213, 212, 'Wikizz', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (214, 369, 'Roombo', '0', 'Ocio y Entretenimineto', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (215, 214, 'Jaloo', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (216, 120, 'Lazz', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (217, 261, 'Lajo', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (218, 248, 'Gigashots', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (219, 208, 'Meetz', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (220, 103, 'Edgeify', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (221, 223, 'Gigashots', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (222, 164, 'Mybuzz', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (223, 276, 'Skyvu', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (224, 91, 'Abata', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (225, 304, 'Quimba', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (226, 262, 'Buzzster', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (227, 195, 'Zoombeat', '0', 'Insignia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (228, 87, 'Mita', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (229, 357, 'Tambee', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (230, 123, 'Kayveo', '1', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (231, 369, 'Devshare', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (232, 319, 'Gabcube', '0', 'Ancla', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (233, 398, 'Meevee', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (234, 202, 'Jayo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (235, 110, 'Edgepulse', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (236, 353, 'Snaptags', '0', 'Conveniencia', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (237, 116, 'Oloo', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (238, 273, 'Flashdog', '0', 'Conveniencia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (239, 189, 'Trunyx', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (240, 264, 'Photofeed', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (241, 348, 'Eayo', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (242, 151, 'Jetpulse', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (243, 119, 'Brainlounge', '0', 'Ancla', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (244, 388, 'Demizz', '0', 'Insignia', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (245, 399, 'Kanoodle', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (246, 253, 'Photobug', '0', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (247, 208, 'Geba', '0', 'Restaurante', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (248, 138, 'Twitterlist', '1', 'Restaurante', 1);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (249, 385, 'Youtags', '0', 'Ocio y Entretenimineto', 2);
insert into A_ESTABLECIMIENTO (id, area, nombre, cerrado, tipo_establecimiento, id_cc) values (250, 258, 'Leexo', '0', 'Restaurante', 2);
