insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (3, 51, '12:44', '19:45', 'Nam dui.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (4, 41, '12:11', '19:58', 'In blandit ultrices enim.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (5, 29, '12:58', '19:05', 'Aenean sit amet justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (6, 92, '12:24', '19:13', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (7, 17, '12:21', '19:55', 'Praesent lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (8, 4, '12:36', '19:37', 'Integer ac neque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (9, 8, '12:16', '19:56', 'Integer ac neque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (10, 93, '12:15', '19:55', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (11, 37, '12:16', '19:55', 'Nulla nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (12, 2, '12:08', '19:32', 'Vivamus vel nulla eget eros elementum pellentesque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (13, 65, '12:31', '19:23', 'Nulla facilisi.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (14, 97, '12:25', '19:44', 'Vivamus vestibulum sagittis sapien.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (15, 18, '12:41', '19:32', 'Aliquam non mauris.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (16, 25, '12:29', '19:27', 'Proin interdum mauris non ligula pellentesque ultrices.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (17, 75, '12:27', '19:19', 'Integer ac neque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (18, 22, '12:39', '19:10', 'Phasellus in felis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (19, 99, '12:58', '19:46', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (20, 63, '12:26', '19:44', 'Nulla suscipit ligula in lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (21, 23, '12:31', '19:35', 'Maecenas ut massa quis augue luctus tincidunt.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (22, 54, '12:21', '19:38', 'Quisque ut erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (23, 93, '12:55', '19:32', 'Duis bibendum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (24, 54, '12:30', '19:41', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (25, 19, '12:11', '19:45', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (26, 39, '12:30', '19:01', 'Fusce consequat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (27, 36, '12:41', '19:07', 'Nam nulla.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (28, 15, '12:47', '19:23', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (29, 16, '12:22', '19:28', 'Morbi non lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (30, 82, '12:18', '19:51', 'Nulla tellus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (31, 52, '12:59', '19:11', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (32, 91, '12:09', '19:28', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (33, 89, '12:30', '19:47', 'Curabitur gravida nisi at nibh.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (34, 93, '12:59', '19:02', 'Suspendisse ornare consequat lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (35, 38, '12:47', '19:19', 'Aliquam erat volutpat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (36, 13, '12:45', '19:40', 'Donec semper sapien a libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (37, 92, '12:13', '19:32', 'Praesent lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (38, 6, '12:06', '19:39', 'Vivamus tortor.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (39, 51, '12:31', '19:55', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (40, 99, '12:24', '19:55', 'Integer a nibh.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (41, 22, '12:19', '19:17', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (42, 13, '12:05', '19:08', 'Mauris lacinia sapien quis libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (43, 63, '12:27', '19:06', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (44, 89, '12:10', '19:57', 'Nulla mollis molestie lorem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (45, 24, '12:16', '19:20', 'Sed vel enim sit amet nunc viverra dapibus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (46, 50, '12:54', '19:58', 'Praesent blandit lacinia erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (47, 82, '12:24', '19:57', 'Pellentesque viverra pede ac diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (48, 35, '12:07', '19:34', 'Donec ut dolor.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (49, 98, '12:19', '19:39', 'In congue.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (50, 47, '12:14', '19:59', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (51, 26, '12:16', '19:38', 'Morbi quis tortor id nulla ultrices aliquet.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (52, 64, '12:09', '19:51', 'Pellentesque viverra pede ac diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (53, 57, '12:38', '19:56', 'Suspendisse ornare consequat lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (54, 43, '12:41', '19:06', 'Nullam molestie nibh in lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (55, 39, '12:02', '19:29', 'Duis ac nibh.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (56, 73, '12:47', '19:14', 'In blandit ultrices enim.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (57, 50, '12:07', '19:46', 'Nulla ut erat id mauris vulputate elementum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (58, 24, '12:30', '19:00', 'Donec ut dolor.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (59, 7, '12:34', '19:51', 'Sed sagittis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (60, 87, '12:56', '19:22', 'Praesent blandit lacinia erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (61, 10, '12:08', '19:00', 'Nulla tellus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (62, 1, '12:59', '19:47', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (63, 74, '12:23', '19:30', 'Nullam varius.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (64, 54, '12:50', '19:02', 'In blandit ultrices enim.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (65, 14, '12:30', '19:18', 'Quisque porta volutpat erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (66, 33, '12:00', '19:08', 'In quis justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (67, 81, '12:00', '19:42', 'In eleifend quam a odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (68, 58, '12:24', '19:06', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (69, 74, '12:53', '19:42', 'Nulla nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (70, 43, '12:43', '19:39', 'Vestibulum sed magna at nunc commodo placerat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (71, 98, '12:20', '19:43', 'Donec semper sapien a libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (72, 51, '12:53', '19:21', 'Quisque ut erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (73, 19, '12:23', '19:46', 'Integer tincidunt ante vel ipsum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (74, 20, '12:54', '19:20', 'Morbi a ipsum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (75, 60, '12:28', '19:04', 'Nullam porttitor lacus at turpis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (76, 91, '12:54', '19:25', 'Suspendisse potenti.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (77, 62, '12:50', '19:28', 'Sed accumsan felis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (78, 79, '12:58', '19:06', 'Integer ac neque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (79, 98, '12:30', '19:20', 'Nulla justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (80, 57, '12:48', '19:41', 'Donec ut mauris eget massa tempor convallis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (81, 15, '12:50', '19:50', 'Etiam faucibus cursus urna.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (82, 34, '12:59', '19:54', 'Suspendisse ornare consequat lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (83, 42, '12:32', '19:04', 'Ut at dolor quis odio consequat varius.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (84, 60, '12:44', '19:33', 'Cras non velit nec nisi vulputate nonummy.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (85, 13, '12:47', '19:34', 'In eleifend quam a odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (86, 17, '12:11', '19:03', 'Quisque ut erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (87, 44, '12:13', '19:15', 'Morbi quis tortor id nulla ultrices aliquet.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (88, 71, '12:11', '19:45', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (89, 80, '12:53', '19:00', 'Praesent blandit lacinia erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (90, 55, '12:31', '19:29', 'Curabitur convallis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (91, 85, '12:13', '19:17', 'In sagittis dui vel nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (92, 54, '12:00', '19:29', 'Phasellus sit amet erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (93, 82, '12:50', '19:29', 'Aenean auctor gravida sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (94, 58, '12:06', '19:22', 'Cras in purus eu magna vulputate luctus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (95, 77, '12:11', '19:36', 'Aenean sit amet justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (96, 71, '12:06', '19:20', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (97, 77, '12:59', '19:35', 'Sed sagittis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (98, 93, '12:07', '19:23', 'Pellentesque eget nunc.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (99, 58, '12:32', '19:01', 'Nulla tellus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (100, 21, '12:33', '19:09', 'Pellentesque at nulla.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (101, 32, '12:18', '19:18', 'Nulla ac enim.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (102, 2, '12:37', '19:42', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (103, 29, '12:12', '19:01', 'Pellentesque ultrices mattis odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (104, 45, '12:31', '19:13', 'Suspendisse accumsan tortor quis turpis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (105, 21, '12:59', '19:44', 'Nulla mollis molestie lorem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (106, 77, '12:54', '19:37', 'Proin risus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (107, 80, '12:29', '19:47', 'Aenean sit amet justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (108, 48, '12:08', '19:30', 'Ut tellus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (109, 11, '12:49', '19:56', 'In hac habitasse platea dictumst.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (110, 71, '12:16', '19:24', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (111, 4, '12:26', '19:17', 'Nulla suscipit ligula in lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (112, 67, '12:44', '19:30', 'Nulla suscipit ligula in lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (113, 74, '12:19', '19:49', 'Integer ac leo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (114, 15, '12:40', '19:47', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (115, 42, '12:24', '19:18', 'Mauris lacinia sapien quis libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (116, 47, '12:25', '19:47', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (117, 68, '12:27', '19:25', 'Suspendisse potenti.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (118, 22, '12:52', '19:48', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (119, 74, '12:07', '19:46', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (120, 26, '12:27', '19:17', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (121, 9, '12:03', '19:40', 'Maecenas ut massa quis augue luctus tincidunt.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (122, 3, '12:19', '19:59', 'Ut at dolor quis odio consequat varius.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (123, 18, '12:58', '19:06', 'Duis consequat dui nec nisi volutpat eleifend.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (124, 40, '12:01', '19:03', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (125, 29, '12:45', '19:50', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (126, 90, '12:37', '19:24', 'Proin at turpis a pede posuere nonummy.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (127, 39, '12:05', '19:06', 'Maecenas ut massa quis augue luctus tincidunt.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (128, 11, '12:18', '19:38', 'Suspendisse ornare consequat lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (129, 63, '12:26', '19:52', 'Nam nulla.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (130, 40, '12:18', '19:00', 'Phasellus in felis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (131, 90, '12:44', '19:59', 'Donec dapibus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (132, 27, '12:08', '19:22', 'Vestibulum rutrum rutrum neque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (133, 85, '12:40', '19:30', 'Proin risus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (134, 9, '12:01', '19:36', 'Mauris sit amet eros.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (135, 91, '12:44', '19:43', 'Donec quis orci eget orci vehicula condimentum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (136, 50, '12:53', '19:16', 'Pellentesque viverra pede ac diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (137, 45, '12:05', '19:46', 'Duis mattis egestas metus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (138, 26, '12:45', '19:21', 'Aliquam quis turpis eget elit sodales scelerisque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (139, 63, '12:38', '19:57', 'Donec vitae nisi.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (140, 92, '12:32', '19:39', 'Nam dui.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (141, 63, '12:32', '19:28', 'Aenean sit amet justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (142, 61, '12:16', '19:37', 'Donec ut mauris eget massa tempor convallis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (143, 77, '12:27', '19:43', 'Aliquam quis turpis eget elit sodales scelerisque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (144, 13, '12:14', '19:25', 'Nulla facilisi.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (145, 6, '12:45', '19:29', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (146, 13, '12:19', '19:11', 'Pellentesque viverra pede ac diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (147, 25, '12:46', '19:35', 'Maecenas rhoncus aliquam lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (148, 18, '12:08', '19:48', 'Proin risus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (149, 79, '12:57', '19:26', 'In congue.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (150, 96, '12:35', '19:35', 'Aenean fermentum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (151, 74, '12:32', '19:47', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (152, 58, '12:01', '19:51', 'Sed ante.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (153, 7, '12:35', '19:37', 'Donec dapibus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (154, 54, '12:32', '19:45', 'Quisque ut erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (155, 98, '12:56', '19:36', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (156, 94, '12:18', '19:43', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (157, 77, '12:59', '19:43', 'Nulla justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (158, 78, '12:43', '19:11', 'Aenean sit amet justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (159, 35, '12:17', '19:08', 'Morbi non lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (160, 52, '12:30', '19:17', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (161, 68, '12:16', '19:40', 'Proin interdum mauris non ligula pellentesque ultrices.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (162, 62, '12:11', '19:48', 'Maecenas tincidunt lacus at velit.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (163, 15, '12:22', '19:12', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (164, 36, '12:40', '19:57', 'Duis at velit eu est congue elementum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (165, 14, '12:06', '19:13', 'Integer tincidunt ante vel ipsum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (166, 12, '12:39', '19:05', 'Sed ante.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (167, 54, '12:59', '19:32', 'Mauris sit amet eros.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (168, 97, '12:27', '19:37', 'In sagittis dui vel nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (169, 41, '12:10', '19:25', 'Morbi ut odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (170, 12, '12:58', '19:31', 'Nulla ut erat id mauris vulputate elementum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (171, 94, '12:19', '19:00', 'Sed sagittis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (172, 21, '12:46', '19:54', 'Praesent lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (173, 1, '12:24', '19:55', 'Nam tristique tortor eu pede.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (174, 14, '12:18', '19:54', 'Praesent id massa id nisl venenatis lacinia.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (175, 34, '12:14', '19:38', 'Cras pellentesque volutpat dui.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (176, 51, '12:20', '19:10', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (177, 46, '12:43', '19:41', 'Nunc nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (178, 79, '12:23', '19:31', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (179, 31, '12:11', '19:31', 'Nulla tempus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (180, 30, '12:12', '19:43', 'Aenean fermentum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (181, 50, '12:53', '19:23', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (182, 13, '12:08', '19:37', 'Suspendisse ornare consequat lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (183, 70, '12:13', '19:07', 'Duis consequat dui nec nisi volutpat eleifend.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (184, 41, '12:18', '19:58', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (185, 55, '12:32', '19:32', 'Nunc nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (186, 98, '12:01', '19:05', 'Curabitur convallis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (187, 8, '12:41', '19:51', 'Aenean auctor gravida sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (188, 38, '12:46', '19:19', 'Integer tincidunt ante vel ipsum.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (189, 84, '12:16', '19:34', 'Maecenas ut massa quis augue luctus tincidunt.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (190, 76, '12:23', '19:32', 'Morbi ut odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (191, 49, '12:31', '19:10', 'In quis justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (192, 100, '12:44', '19:30', 'Etiam justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (193, 46, '12:02', '19:06', 'Donec ut mauris eget massa tempor convallis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (194, 41, '12:54', '19:05', 'Suspendisse potenti.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (195, 2, '12:38', '19:09', 'Aenean sit amet justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (196, 53, '12:12', '19:28', 'In hac habitasse platea dictumst.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (197, 91, '12:13', '19:47', 'Sed sagittis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (198, 41, '12:59', '19:51', 'Sed accumsan felis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (199, 89, '12:42', '19:39', 'Suspendisse potenti.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (200, 27, '12:04', '19:17', 'Curabitur gravida nisi at nibh.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (201, 11, '12:54', '19:57', 'Pellentesque eget nunc.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (202, 36, '12:03', '19:02', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (203, 68, '12:12', '19:28', 'Phasellus sit amet erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (204, 36, '12:19', '19:14', 'Praesent blandit lacinia erat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (205, 36, '12:47', '19:14', 'Pellentesque eget nunc.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (206, 81, '12:41', '19:45', 'Pellentesque eget nunc.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (207, 81, '12:06', '19:29', 'Mauris lacinia sapien quis libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (208, 7, '12:06', '19:54', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (209, 56, '12:09', '19:01', 'Ut tellus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (210, 41, '12:07', '19:47', 'Pellentesque ultrices mattis odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (211, 45, '12:33', '19:18', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (212, 5, '12:14', '19:25', 'Donec semper sapien a libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (213, 39, '12:05', '19:04', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (214, 92, '12:11', '19:05', 'In eleifend quam a odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (215, 57, '12:13', '19:22', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (216, 20, '12:13', '19:14', 'Duis mattis egestas metus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (217, 57, '12:51', '19:21', 'Suspendisse ornare consequat lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (218, 25, '12:44', '19:22', 'Proin eu mi.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (219, 49, '12:53', '19:16', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (220, 70, '12:37', '19:03', 'Cras in purus eu magna vulputate luctus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (221, 91, '12:24', '19:57', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (222, 75, '12:54', '19:59', 'Vestibulum sed magna at nunc commodo placerat.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (223, 53, '12:26', '19:29', 'Etiam justo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (224, 100, '12:25', '19:56', 'Mauris lacinia sapien quis libero.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (225, 29, '12:50', '19:31', 'Integer ac neque.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (226, 97, '12:56', '19:30', 'Morbi non lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (227, 5, '12:32', '19:05', 'Maecenas ut massa quis augue luctus tincidunt.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (228, 78, '12:32', '19:57', 'Suspendisse potenti.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (229, 75, '12:02', '19:38', 'In congue.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (230, 73, '12:08', '19:45', 'Fusce posuere felis sed lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (231, 86, '12:05', '19:23', 'In blandit ultrices enim.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (232, 27, '12:36', '19:10', 'Aenean auctor gravida sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (233, 43, '12:33', '19:04', 'Maecenas pulvinar lobortis est.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (234, 91, '12:56', '19:02', 'Aenean lectus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (235, 81, '12:52', '19:13', 'In hac habitasse platea dictumst.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (236, 25, '12:33', '19:54', 'Curabitur in libero ut massa volutpat convallis.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (237, 25, '12:55', '19:14', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (238, 100, '12:20', '19:25', 'Integer ac leo.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (239, 18, '12:45', '19:53', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (240, 46, '12:39', '19:29', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (241, 11, '12:08', '19:51', 'Nam tristique tortor eu pede.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (242, 16, '12:20', '19:38', 'Maecenas tincidunt lacus at velit.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (243, 80, '12:00', '19:31', 'Cras pellentesque volutpat dui.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (244, 38, '12:08', '19:04', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (245, 22, '12:13', '19:35', 'Curabitur gravida nisi at nibh.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (246, 68, '12:21', '19:23', 'In sagittis dui vel nisl.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (247, 9, '12:17', '19:57', 'Fusce posuere felis sed lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (248, 1, '12:43', '19:23', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (249, 72, '12:15', '19:48', 'Nulla suscipit ligula in lacus.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (250, 13, '12:27', '19:41', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (251, 30, '12:01', '19:06', 'Mauris sit amet eros.', 'Verde', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, color, tipo_lugar) values (252, 15, '12:30', '19:44', 'Donec quis orci eget orci vehicula condimentum.', 'Verde', 1);
