create sequence aforo_sequence;

--tablas
CREATE TABLE A_TIPO_VISITANTE(
    TIPO_VISITANTE VARCHAR(255) NOT NULL,
    HORARIO VARCHAR(30) NOT NULL
    CONSTRAINT A_TIPO_VISITANTE_PK PRIMARY KEY(TIPO_VISITANTE)
);
CREATE TABLE A_TIPO_LUGAR(
    TIPO_LUGAR VARCHAR(255) NOT NULL,
    CONS_AFORO VARCHAR(30) NOT NULL,
    CONSTRAINT A_TIPO_LUGAR_PK PRIMARY KEY(TIPO_LUGAR)
);
ALTER TABLE
ADD CONSTRAINT CK_CONS_AFORO
CHECK(CONS_AFORO>=0)
ENABLE;

CREATE TABLE A_CENTRO_COMERCIAL
(ID NUMBER,
CIUDAD VARCHAR2(255 BYTE) NOT NULL,
DIRECCION VARCHAR2(255 BYTE) NOT NULL,
CONSTRAINT A_CENTROCOMERCIAL_PK PRIMARY KEY (ID)
);
ALTER TABLE A_CENTRO_COMERCIAL
ADD CONSTRAINT FK_CC_ESPACIO
FOREIGN KEY (ID)
REFERENCES A_ESPACIO(ID)
ENABLE;

CREATE TABLE A_ESPACIO
(ID NUMBER,
CAPACIDAD_ORIGINAL NUMBER NOT NULL,
HORA_APERTURA VARCHAR(10) NOT NULL,
HORA_CIERRE  VARCHAR(10) NULL,
DESCRIPCION VARCHAR2(255 BYTE),
TIPO_LUGAR VARCHAR(255)
CONSTRAINT A_ESPACIO_PK PRIMARY KEY (ID)
);
ALTER TABLE A_ESPACIO
ADD CONSTRAINT FK_TIPO_LUGAR
FOREIGN KEY (TIPO_LUGAR)
REFERENCES A_TIPO_LUGAR(TIPO_LUGAR)
ENABLE;
ALTER TABLE A_ESPACIO
ADD CONSTRAINT CK_CAPACIDAD
CHECK (CAPACIDAD_ORIGINAL >=0)
ENABLE;

CREATE TABLE A_ESTABLECIMIENTO
(ID NUMBER,
AREA NUMBER NOT NULL,
NOMBRE VARCHAR2(255 BYTE),
ID_CC NUMBER,
CONSTRAINT A_ESTABLECIMIENTO_PK PRIMARY KEY (ID)
);
ALTER TABLE A_ESTABLECIMIENTO
ADD CONSTRAINT FK_ESTABLECIMIENTO_ESPACIO
FOREIGN KEY (ID)
REFERENCES A_ESPACIO(ID)
ENABLE;

ALTER TABLE A_ESTABLECIMIENTO
ADD CONSTRAINT CK_AREA
CHECK (AREA >=0)
ENABLE;

ALTER TABLE A_ESTABLECIMIENTO
ADD CONSTRAINT FK_ESTABLECIMIENTO_CC
FOREIGN KEY(ID_CC)
REFERENCES A_CENTROCOMERCIAL(ID)
ENABLE;

CREATE TABLE A_VISITANTE
(ID NUMBER,
TIPO_IDENTIFICACION VARCHAR(10) NOT NULL,
NOMBRE VARCHAR2(255 BYTE) NOT NULL,
CORREO VARCHAR2(255 BYTE),
TELEFONO VARCHAR(255) NOT NULL,
NOMBRE_CONTACTO VARCHAR2(255 BYTE) NOT NULL,
TELEFONO_CONTACTO VARCHAR(255),
TIPO VARCHAR2(255 BYTE),
CONSTRAINT A_VISITANTE_PK PRIMARY KEY (ID)
);

ALTER TABLE A_VISITANTE
ADD CONSTRAINT CK_TELEFONO
CHECK(TELEFONO >=0)
ENABLE;

ALTER TABLE A_VISITANTE
ADD CONSTRAINT CK_TELEFONOCONTACTO
CHECK(TELEFONO_CONTACTO >=0)
ENABLE;

CREATE TABLE A_LECTOR_CARNET
(ID NUMBER,
ID_ESPACIO NUMBER,
ID_VISITANTE NUMBER,
HORA_INGRESO VARCHAR(10) NOT NULL,
HORA_SALIDA VARCHAR(10) NOT NULL,
CONSTRAINT A_LECTOR_CARNET_PK PRIMARY KEY (ID,ID_ESPACIO,ID_VISITANTE)
);

ALTER TABLE A_LECTOR_CARNET
ADD CONSTRAINT FK_LECTOR_ESPACIO
FOREIGN KEY (ID_ESPACIO)
REFERENCES A_ESPACIO(ID)
ENABLE;

ALTER TABLE A_LECTOR_CARNET
ADD CONSTRAINT FK_LECTOR_VISITANTE
FOREIGN KEY (ID_VISITANTE)
REFERENCES A_VISITANTE(ID)
ENABLE;

CREATE TABLE A_AFORO_MAXIMO(
    TIPO_ESPACIO VARCHAR(20),
    AFORO_MAXIMO NUMBER NOT NULL,
    CONSTRAINT A_AFOROMAXIMO_PK PRIMARY KEY (TIPO_ESPACIO),
    ID_ESPACIO NUMBER
);
ALTER TABLE A_AFORO_MAXIMO
ADD CONSTRAINT CK_AFORO_MAXIMO
CHECK (AFORO_MAXIMO >= 0)
ENABLE;
ALTER TABLE A_AFORO_MAXIMO
ADD CONSTRAINT FK_AFORO_MAXIMO_ESPACIO
FOREIGN KEY (ID_ESPACIO)
REFERENCES A_ESPACIO(ID)
ENABLE;
CREATE TABLE A_AFORO_ACTUAL(
    NUM_VISITANTES NUMBER NOT NULL,
    HORA_ACTUAL VARCHAR(20),
    ID_ESPACIO NUMBER,
    CONSTRAINT A_AFOROACTUAL_PK PRIMARY KEY (NUM_VISITANTES,ID_ESPACIO)
);
ALTER TABLE A_AFORO_ACTUAL
ADD CONSTRAINT CK_VISITANTES
CHECK (NUM_VISITANTES >=0)
ENABLE;
ALTER TABLE A_AFORO_ACTUAL
ADD CONSTRAINT FK_AFORO_ACTUAL_ESPACIO
FOREIGN KEY (ID_ESPACIO)
REFERENCES A_ESPACIO(ID)
ENABLE;
COMMIT;