insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (216, 5355, '6:12 AM', '9:03 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (217, 5030, '6:09 AM', '9:26 PM', 'In eleifend quam a odio.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (218, 4452, '6:17 AM', '9:02 PM', 'Duis bibendum.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (219, 5201, '6:28 AM', '9:07 PM', 'Quisque ut erat.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (220, 4110, '6:11 AM', '9:08 PM', 'Proin interdum mauris non ligula pellentesque ultrices.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (221, 4946, '6:25 AM', '9:03 PM', 'Vivamus in felis eu sapien cursus vestibulum.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (222, 5032, '6:18 AM', '9:03 PM', 'Duis mattis egestas metus.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (223, 5737, '6:25 AM', '9:11 PM', 'Sed ante.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (224, 3169, '6:18 AM', '9:19 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (225, 5835, '6:28 AM', '9:09 PM', 'Pellentesque viverra pede ac diam.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (226, 3534, '6:09 AM', '9:19 PM', 'Nulla ut erat id mauris vulputate elementum.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (227, 3126, '6:29 AM', '9:23 PM', 'Nulla tellus.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (228, 4538, '6:15 AM', '9:01 PM', 'Quisque ut erat.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (229, 5583, '6:01 AM', '9:19 PM', 'Praesent blandit lacinia erat.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (230, 4088, '6:19 AM', '9:11 PM', 'Maecenas pulvinar lobortis est.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (231, 5251, '6:11 AM', '9:16 PM', 'Nunc purus.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (232, 5465, '6:16 AM', '9:24 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (233, 3344, '6:05 AM', '9:13 PM', 'Donec posuere metus vitae ipsum.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (234, 3942, '6:26 AM', '9:21 PM', 'Suspendisse accumsan tortor quis turpis.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (235, 4365, '6:24 AM', '9:05 PM', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (236, 3393, '6:20 AM', '9:26 PM', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (237, 5790, '6:09 AM', '9:25 PM', 'Nam nulla.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (238, 3903, '6:06 AM', '9:13 PM', 'Nunc nisl.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (239, 4412, '6:26 AM', '9:24 PM', 'Sed sagittis.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (240, 3956, '6:12 AM', '9:22 PM', 'Mauris ullamcorper purus sit amet nulla.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (241, 4428, '6:08 AM', '9:13 PM', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (242, 4002, '6:28 AM', '9:06 PM', 'Curabitur gravida nisi at nibh.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (243, 3201, '6:23 AM', '9:05 PM', 'In hac habitasse platea dictumst.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (244, 3056, '6:04 AM', '9:21 PM', 'Nam nulla.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (245, 5900, '6:17 AM', '9:24 PM', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (246, 4877, '6:05 AM', '9:29 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (247, 3039, '6:10 AM', '9:02 PM', 'Mauris sit amet eros.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (248, 3046, '6:19 AM', '9:25 PM', 'Proin interdum mauris non ligula pellentesque ultrices.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (249, 3033, '6:19 AM', '9:02 PM', 'Integer tincidunt ante vel ipsum.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (250, 4787, '6:19 AM', '9:22 PM', 'Vivamus tortor.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (251, 5057, '6:06 AM', '9:13 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (252, 4818, '6:13 AM', '9:19 PM', 'Sed sagittis.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (253, 4638, '6:25 AM', '9:23 PM', 'Suspendisse ornare consequat lectus.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (254, 4626, '6:23 AM', '9:19 PM', 'Nulla nisl.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (255, 5482, '6:08 AM', '9:09 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (256, 5870, '6:01 AM', '9:21 PM', 'In eleifend quam a odio.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (257, 3687, '6:06 AM', '9:24 PM', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (258, 5244, '6:23 AM', '9:20 PM', 'Nam nulla.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (259, 4363, '6:02 AM', '9:06 PM', 'Cras pellentesque volutpat dui.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (260, 5396, '6:23 AM', '9:05 PM', 'Fusce posuere felis sed lacus.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (261, 5771, '6:15 AM', '9:10 PM', 'Morbi non lectus.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (262, 5251, '6:02 AM', '9:27 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (263, 5236, '6:11 AM', '9:27 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (264, 3317, '6:13 AM', '9:25 PM', 'Fusce posuere felis sed lacus.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (265, 5768, '6:19 AM', '9:23 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (266, 5550, '6:18 AM', '9:21 PM', 'Sed vel enim sit amet nunc viverra dapibus.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (267, 3451, '6:00 AM', '9:25 PM', 'Donec vitae nisi.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (268, 3756, '6:16 AM', '9:05 PM', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (269, 4073, '6:03 AM', '9:05 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (270, 4623, '6:03 AM', '9:23 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (271, 4322, '6:14 AM', '9:23 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (272, 5963, '6:15 AM', '9:12 PM', 'Suspendisse ornare consequat lectus.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (273, 4697, '6:24 AM', '9:14 PM', 'Donec ut dolor.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (274, 5129, '6:05 AM', '9:16 PM', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (275, 5774, '6:18 AM', '9:17 PM', 'Nulla nisl.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (276, 4868, '6:14 AM', '9:10 PM', 'Nulla suscipit ligula in lacus.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (277, 4547, '6:00 AM', '9:26 PM', 'Donec vitae nisi.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (278, 5663, '6:23 AM', '9:03 PM', 'Vestibulum rutrum rutrum neque.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (279, 5127, '6:28 AM', '9:01 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (280, 3494, '6:22 AM', '9:19 PM', 'Nulla nisl.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (281, 5572, '6:29 AM', '9:13 PM', 'In eleifend quam a odio.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (282, 3046, '6:25 AM', '9:06 PM', 'Maecenas tincidunt lacus at velit.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (283, 5941, '6:17 AM', '9:00 PM', 'Quisque porta volutpat erat.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (284, 3536, '6:11 AM', '9:08 PM', 'In hac habitasse platea dictumst.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (285, 4702, '6:28 AM', '9:00 PM', 'Aenean auctor gravida sem.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (286, 5953, '6:28 AM', '9:28 PM', 'Donec posuere metus vitae ipsum.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (287, 5538, '6:23 AM', '9:17 PM', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (288, 4653, '6:04 AM', '9:16 PM', 'Fusce consequat.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (289, 4221, '6:13 AM', '9:00 PM', 'Duis aliquam convallis nunc.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (290, 3478, '6:04 AM', '9:08 PM', 'Morbi non quam nec dui luctus rutrum.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (291, 3883, '6:27 AM', '9:22 PM', 'Phasellus id sapien in sapien iaculis congue.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (292, 3589, '6:08 AM', '9:29 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (293, 4133, '6:04 AM', '9:26 PM', 'Proin eu mi.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (294, 4394, '6:20 AM', '9:17 PM', 'Morbi porttitor lorem id ligula.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (295, 5973, '6:22 AM', '9:01 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (296, 4676, '6:14 AM', '9:20 PM', 'Donec posuere metus vitae ipsum.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (297, 4898, '6:19 AM', '9:15 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (298, 5817, '6:02 AM', '9:02 PM', 'Etiam justo.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (299, 4025, '6:00 AM', '9:18 PM', 'Sed accumsan felis.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (300, 5929, '6:18 AM', '9:08 PM', 'In blandit ultrices enim.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (301, 3306, '6:16 AM', '9:20 PM', 'Integer ac neque.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (302, 3347, '6:03 AM', '9:24 PM', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (303, 4011, '6:05 AM', '9:10 PM', 'Proin at turpis a pede posuere nonummy.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (304, 4746, '6:03 AM', '9:05 PM', 'Donec semper sapien a libero.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (305, 4151, '6:28 AM', '9:21 PM', 'Curabitur convallis.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (306, 5063, '6:20 AM', '9:22 PM', 'Vestibulum sed magna at nunc commodo placerat.', 6);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (307, 3280, '6:21 AM', '9:17 PM', 'Duis at velit eu est congue elementum.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (308, 5506, '6:16 AM', '9:26 PM', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (309, 4150, '6:04 AM', '9:08 PM', 'Morbi a ipsum.', 5);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (310, 3498, '6:13 AM', '9:00 PM', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (311, 3681, '6:04 AM', '9:00 PM', 'Quisque porta volutpat erat.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (312, 4212, '6:13 AM', '9:11 PM', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 3);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (313, 4906, '6:14 AM', '9:23 PM', 'Praesent blandit lacinia erat.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (314, 4789, '6:05 AM', '9:00 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 4);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (315, 4504, '6:21 AM', '9:10 PM', 'Sed ante.', 6);
