insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (1, 3709, '6:29 AM', '9:25 PM', 'Suspendisse potenti.', 966);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (2, 3989, '6:18 AM', '9:24 PM', 'Suspendisse potenti.', 562);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (3, 3227, '6:03 AM', '9:12 PM', 'Nam tristique tortor eu pede.', 535);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (4, 3856, '6:22 AM', '9:21 PM', 'Nulla justo.', 386);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (5, 3531, '6:01 AM', '9:25 PM', 'In congue.', 439);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (6, 3421, '6:03 AM', '9:27 PM', 'Fusce consequat.', 487);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (7, 3150, '6:27 AM', '9:09 PM', 'Cras pellentesque volutpat dui.', 223);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (8, 3833, '6:09 AM', '9:23 PM', 'Pellentesque ultrices mattis odio.', 663);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (9, 3212, '6:07 AM', '9:07 PM', 'Morbi ut odio.', 151);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (10, 3540, '6:26 AM', '9:18 PM', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 719);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (11, 3195, '6:14 AM', '9:28 PM', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 139);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (12, 3777, '6:01 AM', '9:04 PM', 'Pellentesque viverra pede ac diam.', 862);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (13, 3869, '6:25 AM', '9:10 PM', 'In hac habitasse platea dictumst.', 567);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (14, 3355, '6:14 AM', '9:10 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 582);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (15, 3593, '6:19 AM', '9:01 PM', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 455);