insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (1, 3114, '6:22 AM', '9:04 PM', 'Pellentesque ultrices mattis odio.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (2, 3942, '6:29 AM', '9:10 PM', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (3, 3917, '6:06 AM', '9:27 PM', 'Praesent blandit lacinia erat.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (4, 5399, '6:21 AM', '9:01 PM', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (5, 3080, '6:10 AM', '9:17 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (6, 3711, '6:24 AM', '9:16 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (7, 4250, '6:22 AM', '9:26 PM', 'Praesent blandit lacinia erat.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (8, 4121, '6:18 AM', '9:00 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (9, 5614, '6:18 AM', '9:25 PM', 'Nulla tempus.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (10, 4621, '6:29 AM', '9:14 PM', 'Mauris lacinia sapien quis libero.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (11, 4983, '6:25 AM', '9:25 PM', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (12, 4320, '6:19 AM', '9:03 PM', 'Duis bibendum.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (13, 3214, '6:29 AM', '9:26 PM', 'Morbi ut odio.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (14, 5822, '6:25 AM', '9:27 PM', 'Curabitur convallis.', 2);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (15, 3261, '6:29 AM', '9:02 PM', 'In sagittis dui vel nisl.', 2);
