insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (16, 33, 'Muller Group', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (17, 22, 'Zulauf-Bergstrom', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (18, 50, 'Marquardt-Blanda', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (19, 88, 'Yundt-O''Conner', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (20, 35, 'Ferry and Sons', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (21, 38, 'Klein-Cronin', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (22, 24, 'Lehner, Reynolds and Stehr', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (23, 33, 'Wolf-Bauch', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (24, 33, 'Swift, Schmidt and Nader', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (25, 77, 'Gislason-Miller', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (26, 93, 'Sawayn, Rohan and Grimes', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (27, 74, 'Block and Sons', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (28, 11, 'Kling Inc', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (29, 58, 'Fadel-Rosenbaum', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (30, 89, 'Fadel LLC', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (31, 86, 'DuBuque Inc', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (32, 14, 'Hodkiewicz LLC', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (33, 10, 'Block-Beer', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (34, 77, 'Keeling, Gerlach and Schumm', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (35, 30, 'Moore, Simonis and Hilpert', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (36, 37, 'O''Connell, Mante and Gusikowski', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (37, 63, 'Cruickshank-Lindgren', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (38, 30, 'Dicki, Flatley and Bednar', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (39, 31, 'Waters, Runte and Wuckert', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (40, 50, 'Gaylord and Sons', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (41, 14, 'Kessler, Feeney and Turcotte', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (42, 12, 'Yost, Jerde and Wehner', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (43, 81, 'Nolan, Cummings and Lebsack', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (44, 91, 'Thompson, Boyle and Kessler', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (45, 82, 'Stark and Sons', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (46, 23, 'Heaney, Langworth and Batz', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (47, 10, 'Bruen, Dach and Swift', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (48, 41, 'Rippin and Sons', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (49, 20, 'Gislason LLC', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (50, 79, 'Watsica, Ruecker and Klein', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (51, 68, 'Doyle, Harvey and Wiza', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (52, 26, 'Marvin-Wilkinson', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (53, 44, 'Fisher, Wiza and Fay', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (54, 33, 'Senger Inc', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (55, 30, 'McDermott LLC', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (56, 78, 'Effertz, Crona and Spencer', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (57, 33, 'Zieme-Brakus', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (58, 22, 'Muller-Ortiz', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (59, 34, 'Torphy, Dicki and Cronin', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (60, 63, 'Marquardt and Sons', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (61, 73, 'O''Hara, Smith and Prohaska', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (62, 55, 'Haley-Gleichner', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (63, 60, 'Hegmann and Sons', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (64, 58, 'Heathcote-Kerluke', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (65, 25, 'Daniel-Hand', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (66, 27, 'Mraz, Reinger and Dickens', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (67, 54, 'Kihn and Sons', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (68, 31, 'Wolf-Brown', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (69, 78, 'Kuhic and Sons', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (70, 29, 'Dibbert and Sons', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (71, 72, 'Homenick, Dach and Lehner', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (72, 31, 'Prosacco-Larkin', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (73, 20, 'Bailey, Prosacco and Runolfsdottir', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (74, 69, 'Wisoky-Swift', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (75, 90, 'Rath LLC', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (76, 79, 'Kertzmann LLC', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (77, 58, 'Nader-Kuhic', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (78, 54, 'Marvin-Gusikowski', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (79, 99, 'Rohan Inc', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (80, 31, 'Cartwright-Bradtke', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (81, 49, 'Breitenberg Inc', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (82, 68, 'Jakubowski-Kuphal', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (83, 59, 'Bauch-Schmitt', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (84, 70, 'Green LLC', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (85, 81, 'Wilderman-Skiles', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (86, 84, 'Murphy, Labadie and Witting', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (87, 67, 'Kuhlman-Senger', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (88, 86, 'Klein, Green and Wisoky', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (89, 52, 'Lehner LLC', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (90, 20, 'Kreiger, Kunde and Jacobson', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (91, 94, 'Sporer and Sons', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (92, 82, 'Wisozk-Kilback', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (93, 99, 'Zboncak-Oberbrunner', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (94, 20, 'Reilly Group', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (95, 92, 'Cole, Christiansen and Murazik', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (96, 30, 'Bailey, Ratke and Wunsch', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (97, 83, 'Kihn-Dooley', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (98, 73, 'Stoltenberg Inc', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (99, 42, 'Prohaska-Doyle', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (100, 78, 'Glover-Gleichner', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (101, 18, 'Rath and Sons', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (102, 76, 'Casper-Abernathy', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (103, 25, 'Fritsch-Trantow', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (104, 99, 'O''Hara, Hudson and Donnelly', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (105, 51, 'Ruecker, Weber and Zieme', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (106, 51, 'Koepp-Lowe', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (107, 12, 'Abbott-Herman', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (108, 92, 'Stark, Larson and Ruecker', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (109, 83, 'Weber Inc', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (110, 60, 'Johnson Inc', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (111, 47, 'Bednar-Quitzon', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (112, 93, 'Wisozk-Farrell', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (113, 94, 'Braun-McKenzie', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (114, 68, 'Thiel and Sons', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (115, 10, 'Waelchi-Macejkovic', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (116, 68, 'Little-Weissnat', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (117, 14, 'Sipes and Sons', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (118, 98, 'Hudson, Schowalter and O''Hara', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (119, 20, 'Weissnat-Kuhlman', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (120, 65, 'Russel and Sons', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (121, 64, 'Treutel, Bailey and D''Amore', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (122, 47, 'Aufderhar, Jones and Davis', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (123, 92, 'McCullough Inc', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (124, 53, 'Yost Group', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (125, 74, 'Tromp-White', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (126, 93, 'Weimann, Hartmann and Hickle', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (127, 73, 'Haag Inc', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (128, 61, 'Berge-Hirthe', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (129, 92, 'Streich, Feest and Funk', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (130, 27, 'Rutherford, Rice and Price', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (131, 36, 'Little-Yundt', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (132, 30, 'Raynor-Eichmann', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (133, 13, 'Ebert Inc', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (134, 91, 'Mosciski and Sons', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (135, 100, 'Wunsch-Murphy', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (136, 76, 'Collier-Metz', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (137, 55, 'Kilback-Wisoky', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (138, 79, 'Mohr, Goyette and Brekke', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (139, 61, 'Jenkins Inc', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (140, 59, 'Carter Inc', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (141, 65, 'Bruen LLC', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (142, 95, 'Schneider-Flatley', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (143, 31, 'Schamberger-Marks', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (144, 38, 'Kris and Sons', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (145, 35, 'Crist and Sons', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (146, 61, 'Beahan and Sons', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (147, 50, 'Pollich-Nitzsche', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (148, 46, 'Dare Inc', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (149, 69, 'Shields-Purdy', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (150, 38, 'Volkman Inc', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (151, 32, 'Will, Stiedemann and Denesik', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (152, 81, 'Cormier, Aufderhar and Kertzmann', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (153, 54, 'Cassin LLC', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (154, 98, 'Marquardt-Watsica', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (155, 54, 'Veum and Sons', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (156, 77, 'Murray LLC', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (157, 68, 'Friesen, Farrell and Breitenberg', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (158, 40, 'Reichel Inc', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (159, 58, 'Witting and Sons', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (160, 57, 'Harber-Altenwerth', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (161, 51, 'Wiza-Pollich', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (162, 78, 'Hoppe-Veum', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (163, 82, 'Beahan Group', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (164, 10, 'Dooley, Kautzer and Sporer', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (165, 25, 'Nitzsche, Rosenbaum and Kovacek', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (166, 94, 'Williamson Inc', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (167, 64, 'Monahan-Dicki', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (168, 58, 'Moore Inc', 3);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (169, 96, 'Hilpert, Beahan and Macejkovic', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (170, 69, 'Dooley-Rosenbaum', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (171, 69, 'Lindgren Inc', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (172, 10, 'Vandervort, Herman and Ledner', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (173, 88, 'Towne-Rogahn', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (174, 64, 'Brown Group', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (175, 98, 'Weimann-Sauer', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (176, 59, 'Beatty, Cronin and Emard', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (177, 97, 'Stiedemann, Spinka and Rosenbaum', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (178, 70, 'Cassin-Emmerich', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (179, 73, 'Batz-Boyle', 10);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (180, 42, 'Nienow-Hettinger', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (181, 74, 'Bechtelar-Schoen', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (182, 62, 'Armstrong, Hills and Welch', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (183, 33, 'Rutherford, Connelly and Krajcik', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (184, 18, 'O''Hara Inc', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (185, 83, 'Schneider Group', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (186, 22, 'Hansen and Sons', 11);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (187, 17, 'Sawayn Inc', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (188, 99, 'Weber Group', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (189, 33, 'Schinner, Hintz and Treutel', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (190, 66, 'Lowe Inc', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (191, 53, 'Zieme, Altenwerth and Kuphal', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (192, 27, 'Nolan, Kessler and Gusikowski', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (193, 66, 'Bailey-Stamm', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (194, 64, 'Stokes Group', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (195, 95, 'Hagenes, Gorczany and Mertz', 7);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (196, 18, 'Mueller, Robel and Botsford', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (197, 57, 'Johns, Rodriguez and Greenholt', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (198, 43, 'Metz-Ryan', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (199, 47, 'Gottlieb, Stehr and Zboncak', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (200, 17, 'White-Greenholt', 5);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (201, 15, 'Rolfson and Sons', 1);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (202, 67, 'Hermann Inc', 4);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (203, 19, 'Wilderman, Mraz and Jaskolski', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (204, 22, 'Ritchie-Goodwin', 12);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (205, 54, 'Towne, Pagac and Douglas', 2);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (206, 76, 'Paucek-Jaskolski', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (207, 52, 'Johnson, Collier and Grant', 9);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (208, 71, 'Franecki Group', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (209, 97, 'Conroy and Sons', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (210, 13, 'West LLC', 13);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (211, 41, 'Strosin-McCullough', 8);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (212, 66, 'Erdman, Becker and Cartwright', 6);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (213, 22, 'Brekke-Ruecker', 14);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (214, 88, 'Reinger, Green and Miller', 15);
insert into A_ESTABLECIMIENTO (ID, AREA, NOMBRE, ID_CC) values (215, 70, 'Legros Inc', 6);
