insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (216, 39, '12:18 PM', '6:14 PM', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (217, 40, '1:22 PM', '6:40 PM', 'Sed accumsan felis.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (218, 35, '2:09 PM', '7:46 PM', 'Maecenas pulvinar lobortis est.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (219, 39, '12:33 PM', '7:54 PM', 'Duis at velit eu est congue elementum.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (220, 19, '1:28 PM', '6:01 PM', 'Aenean auctor gravida sem.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (221, 12, '12:31 PM', '7:57 PM', 'Sed ante.', 3);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (222, 36, '12:17 PM', '7:51 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (223, 35, '1:04 PM', '7:00 PM', 'Nulla justo.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (224, 18, '1:51 PM', '6:30 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (225, 14, '2:40 PM', '6:47 PM', 'Aliquam non mauris.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (226, 21, '2:37 PM', '7:48 PM', 'Proin eu mi.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (227, 41, '12:43 PM', '7:21 PM', 'Ut tellus.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (228, 18, '2:53 PM', '6:27 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (229, 15, '1:09 PM', '6:08 PM', 'Morbi vel lectus in quam fringilla rhoncus.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (230, 17, '2:50 PM', '7:02 PM', 'Vestibulum sed magna at nunc commodo placerat.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (231, 44, '2:52 PM', '7:55 PM', 'Suspendisse potenti.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (232, 34, '1:34 PM', '6:13 PM', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (233, 39, '12:52 PM', '6:59 PM', 'Mauris lacinia sapien quis libero.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (234, 11, '12:27 PM', '7:40 PM', 'Aenean fermentum.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (235, 25, '12:22 PM', '7:38 PM', 'Morbi a ipsum.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (236, 17, '2:19 PM', '6:10 PM', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (237, 13, '12:52 PM', '6:35 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 25);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (238, 37, '2:22 PM', '7:44 PM', 'Nam tristique tortor eu pede.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (239, 33, '2:39 PM', '7:02 PM', 'Praesent id massa id nisl venenatis lacinia.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (240, 15, '1:16 PM', '6:37 PM', 'Morbi non quam nec dui luctus rutrum.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (241, 23, '2:07 PM', '7:20 PM', 'Suspendisse ornare consequat lectus.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (242, 29, '2:57 PM', '6:28 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (243, 14, '1:41 PM', '7:06 PM', 'Suspendisse potenti.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (244, 27, '2:29 PM', '6:57 PM', 'Morbi ut odio.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (245, 47, '2:07 PM', '6:52 PM', 'Ut at dolor quis odio consequat varius.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (246, 17, '1:45 PM', '7:19 PM', 'Curabitur at ipsum ac tellus semper interdum.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (247, 47, '2:27 PM', '7:04 PM', 'Vivamus vestibulum sagittis sapien.', 15);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (248, 28, '2:35 PM', '7:19 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (249, 43, '2:43 PM', '7:35 PM', 'Nulla tellus.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (250, 37, '1:06 PM', '7:42 PM', 'Ut tellus.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (251, 47, '2:25 PM', '6:54 PM', 'Phasellus id sapien in sapien iaculis congue.', 15);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (252, 50, '1:36 PM', '6:26 PM', 'In congue.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (253, 33, '1:54 PM', '6:13 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (254, 26, '12:01 PM', '6:16 PM', 'Aenean auctor gravida sem.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (255, 28, '2:14 PM', '6:42 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (256, 28, '12:01 PM', '6:56 PM', 'Nulla tellus.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (257, 15, '12:11 PM', '6:18 PM', 'Nulla ut erat id mauris vulputate elementum.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (258, 19, '1:54 PM', '6:52 PM', 'In sagittis dui vel nisl.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (259, 32, '1:21 PM', '7:41 PM', 'Aenean lectus.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (260, 36, '2:25 PM', '6:42 PM', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (261, 14, '1:56 PM', '7:43 PM', 'Maecenas pulvinar lobortis est.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (262, 39, '1:08 PM', '6:41 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (263, 19, '1:20 PM', '7:31 PM', 'Mauris sit amet eros.', 8);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (264, 26, '2:06 PM', '7:57 PM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (265, 46, '12:41 PM', '6:14 PM', 'Pellentesque ultrices mattis odio.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (266, 15, '1:38 PM', '6:42 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (267, 14, '12:56 PM', '7:04 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (268, 17, '2:59 PM', '6:27 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (269, 17, '1:34 PM', '6:24 PM', 'Nunc rhoncus dui vel sem.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (270, 36, '1:23 PM', '7:49 PM', 'Ut tellus.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (271, 50, '1:47 PM', '6:42 PM', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (272, 14, '11:59 AM', '7:09 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (273, 29, '12:54 PM', '7:24 PM', 'Etiam vel augue.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (274, 39, '12:23 PM', '6:35 PM', 'Mauris lacinia sapien quis libero.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (275, 25, '1:12 PM', '6:24 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (276, 50, '2:19 PM', '6:31 PM', 'Aenean fermentum.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (277, 49, '12:55 PM', '7:17 PM', 'Mauris lacinia sapien quis libero.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (278, 33, '1:55 PM', '7:10 PM', 'Praesent id massa id nisl venenatis lacinia.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (279, 37, '1:30 PM', '6:46 PM', 'Curabitur convallis.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (280, 24, '12:58 PM', '6:06 PM', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (281, 16, '2:48 PM', '6:29 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (282, 35, '11:59 AM', '6:39 PM', 'Donec quis orci eget orci vehicula condimentum.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (283, 38, '1:39 PM', '7:50 PM', 'Nunc nisl.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (284, 25, '1:26 PM', '7:41 PM', 'Suspendisse potenti.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (285, 46, '2:30 PM', '7:25 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 8);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (286, 38, '2:49 PM', '7:19 PM', 'Fusce posuere felis sed lacus.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (287, 33, '2:16 PM', '6:25 PM', 'Etiam vel augue.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (288, 47, '2:12 PM', '6:19 PM', 'Sed sagittis.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (289, 19, '12:02 PM', '6:13 PM', 'Aenean auctor gravida sem.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (290, 43, '2:44 PM', '6:42 PM', 'Ut at dolor quis odio consequat varius.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (291, 12, '12:14 PM', '6:09 PM', 'Praesent lectus.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (292, 49, '12:44 PM', '6:58 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (293, 40, '2:29 PM', '6:10 PM', 'Aliquam erat volutpat.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (294, 25, '12:24 PM', '7:31 PM', 'Aenean fermentum.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (295, 25, '1:16 PM', '7:10 PM', 'Donec vitae nisi.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (296, 11, '2:41 PM', '6:42 PM', 'Morbi vel lectus in quam fringilla rhoncus.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (297, 19, '1:37 PM', '6:31 PM', 'Aenean sit amet justo.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (298, 34, '1:57 PM', '7:35 PM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (299, 35, '12:51 PM', '6:01 PM', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (300, 31, '2:36 PM', '6:28 PM', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (301, 25, '12:35 PM', '7:03 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (302, 42, '12:03 PM', '6:35 PM', 'Donec quis orci eget orci vehicula condimentum.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (303, 32, '2:24 PM', '6:13 PM', 'Pellentesque viverra pede ac diam.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (304, 36, '12:47 PM', '7:23 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (305, 30, '1:36 PM', '6:28 PM', 'Nunc rhoncus dui vel sem.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (306, 48, '2:33 PM', '7:34 PM', 'Donec posuere metus vitae ipsum.', 25);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (307, 15, '2:41 PM', '7:59 PM', 'Phasellus sit amet erat.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (308, 13, '12:41 PM', '6:15 PM', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (309, 26, '1:10 PM', '6:17 PM', 'Proin eu mi.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (310, 17, '2:16 PM', '7:50 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (311, 18, '2:52 PM', '7:58 PM', 'Vestibulum ac est lacinia nisi venenatis tristique.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (312, 38, '1:25 PM', '7:43 PM', 'Donec posuere metus vitae ipsum.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (313, 37, '2:07 PM', '6:59 PM', 'Integer ac neque.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (314, 22, '2:29 PM', '7:20 PM', 'Nunc purus.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (315, 14, '2:47 PM', '7:36 PM', 'Fusce consequat.', 13);
