insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (16, 86, '12:58 PM', '7:07 PM', 'Maecenas tincidunt lacus at velit.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (17, 49, '2:39 PM', '7:44 PM', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 35);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (18, 64, '1:23 PM', '7:12 PM', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (19, 49, '1:10 PM', '7:39 PM', 'Duis mattis egestas metus.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (20, 99, '12:31 PM', '7:11 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (21, 52, '1:09 PM', '7:10 PM', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (22, 73, '2:20 PM', '6:13 PM', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (23, 97, '1:26 PM', '6:15 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (24, 94, '12:59 PM', '7:21 PM', 'Integer ac leo.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (25, 58, '2:00 PM', '6:31 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (26, 90, '2:47 PM', '7:08 PM', 'Integer tincidunt ante vel ipsum.', 38);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (27, 44, '12:44 PM', '7:49 PM', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (28, 47, '12:15 PM', '7:09 PM', 'Donec ut mauris eget massa tempor convallis.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (29, 53, '2:50 PM', '7:06 PM', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (30, 64, '12:08 PM', '7:58 PM', 'Maecenas ut massa quis augue luctus tincidunt.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (31, 96, '1:10 PM', '7:49 PM', 'Vivamus vel nulla eget eros elementum pellentesque.', 38);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (32, 98, '2:23 PM', '7:04 PM', 'Donec posuere metus vitae ipsum.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (33, 51, '1:58 PM', '7:15 PM', 'Nam dui.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (34, 50, '12:06 PM', '6:55 PM', 'Nulla ut erat id mauris vulputate elementum.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (35, 80, '1:37 PM', '7:58 PM', 'Nam dui.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (36, 98, '12:48 PM', '6:34 PM', 'Morbi non quam nec dui luctus rutrum.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (37, 67, '12:15 PM', '6:57 PM', 'Proin risus.', 8);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (38, 90, '12:32 PM', '7:30 PM', 'Donec semper sapien a libero.', 33);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (39, 53, '12:51 PM', '6:42 PM', 'Maecenas tincidunt lacus at velit.', 29);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (40, 98, '1:35 PM', '7:12 PM', 'Fusce posuere felis sed lacus.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (41, 67, '1:22 PM', '7:21 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (42, 47, '2:13 PM', '6:09 PM', 'In hac habitasse platea dictumst.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (43, 96, '12:04 PM', '7:11 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 15);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (44, 78, '2:38 PM', '7:23 PM', 'Mauris sit amet eros.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (45, 57, '2:26 PM', '6:16 PM', 'Proin at turpis a pede posuere nonummy.', 38);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (46, 66, '2:40 PM', '7:12 PM', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 26);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (47, 90, '1:58 PM', '6:30 PM', 'Cras non velit nec nisi vulputate nonummy.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (48, 53, '1:06 PM', '6:57 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (49, 86, '1:25 PM', '7:09 PM', 'Curabitur in libero ut massa volutpat convallis.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (50, 87, '2:33 PM', '6:34 PM', 'Aenean sit amet justo.', 32);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (51, 100, '1:16 PM', '6:40 PM', 'Mauris sit amet eros.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (52, 70, '2:37 PM', '6:00 PM', 'Nullam molestie nibh in lectus.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (53, 82, '12:10 PM', '6:19 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 35);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (54, 61, '1:07 PM', '7:34 PM', 'Duis ac nibh.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (55, 94, '2:09 PM', '6:16 PM', 'Donec ut mauris eget massa tempor convallis.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (56, 88, '1:47 PM', '7:28 PM', 'Integer tincidunt ante vel ipsum.', 40);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (57, 74, '1:46 PM', '7:41 PM', 'Morbi non quam nec dui luctus rutrum.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (58, 43, '12:30 PM', '7:16 PM', 'Pellentesque at nulla.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (59, 82, '2:03 PM', '6:27 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (60, 62, '12:35 PM', '6:22 PM', 'In hac habitasse platea dictumst.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (61, 50, '2:40 PM', '6:26 PM', 'Duis at velit eu est congue elementum.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (62, 70, '12:21 PM', '6:17 PM', 'Curabitur at ipsum ac tellus semper interdum.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (63, 67, '12:32 PM', '6:11 PM', 'Nulla tellus.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (64, 96, '1:04 PM', '6:42 PM', 'Aenean lectus.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (65, 93, '2:42 PM', '7:17 PM', 'Aliquam erat volutpat.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (66, 65, '2:17 PM', '6:49 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (67, 41, '12:28 PM', '7:53 PM', 'Suspendisse accumsan tortor quis turpis.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (68, 46, '12:19 PM', '7:48 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (69, 93, '12:07 PM', '6:38 PM', 'Mauris ullamcorper purus sit amet nulla.', 33);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (70, 47, '2:07 PM', '7:41 PM', 'In sagittis dui vel nisl.', 29);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (71, 100, '2:01 PM', '6:24 PM', 'In hac habitasse platea dictumst.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (72, 59, '12:40 PM', '6:31 PM', 'Etiam faucibus cursus urna.', 8);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (73, 41, '12:50 PM', '6:25 PM', 'Proin eu mi.', 31);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (74, 88, '12:38 PM', '7:40 PM', 'Pellentesque ultrices mattis odio.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (75, 80, '2:39 PM', '7:09 PM', 'Aenean sit amet justo.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (76, 45, '2:07 PM', '6:54 PM', 'Vestibulum ac est lacinia nisi venenatis tristique.', 31);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (77, 74, '1:37 PM', '7:00 PM', 'In quis justo.', 25);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (78, 87, '12:39 PM', '7:16 PM', 'Vestibulum sed magna at nunc commodo placerat.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (79, 44, '12:38 PM', '7:15 PM', 'Vivamus in felis eu sapien cursus vestibulum.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (80, 85, '12:26 PM', '6:28 PM', 'Aenean sit amet justo.', 27);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (81, 88, '12:33 PM', '7:28 PM', 'Proin at turpis a pede posuere nonummy.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (82, 48, '2:02 PM', '6:40 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (83, 68, '1:52 PM', '7:34 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (84, 45, '2:51 PM', '7:31 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (85, 93, '2:07 PM', '7:02 PM', 'Duis consequat dui nec nisi volutpat eleifend.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (86, 56, '2:16 PM', '6:39 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (87, 45, '12:15 PM', '6:38 PM', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (88, 74, '2:56 PM', '6:45 PM', 'Aenean auctor gravida sem.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (89, 92, '12:58 PM', '7:57 PM', 'Phasellus in felis.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (90, 45, '12:13 PM', '6:30 PM', 'Nulla mollis molestie lorem.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (91, 86, '1:49 PM', '6:29 PM', 'Vivamus tortor.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (92, 76, '2:02 PM', '7:25 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (93, 64, '1:19 PM', '6:32 PM', 'Integer ac neque.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (94, 94, '12:06 PM', '7:07 PM', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (95, 97, '1:20 PM', '7:35 PM', 'Curabitur gravida nisi at nibh.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (96, 61, '2:47 PM', '6:27 PM', 'In congue.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (97, 90, '12:08 PM', '7:55 PM', 'Ut at dolor quis odio consequat varius.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (98, 94, '2:46 PM', '6:07 PM', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (99, 48, '2:20 PM', '6:46 PM', 'In eleifend quam a odio.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (100, 45, '12:58 PM', '7:06 PM', 'In eleifend quam a odio.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (101, 71, '12:03 PM', '6:06 PM', 'Integer ac leo.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (102, 54, '12:51 PM', '7:52 PM', 'In eleifend quam a odio.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (103, 96, '1:03 PM', '6:55 PM', 'Aenean fermentum.', 33);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (104, 50, '12:12 PM', '7:45 PM', 'Nulla tellus.', 39);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (105, 71, '12:41 PM', '6:38 PM', 'In hac habitasse platea dictumst.', 33);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (106, 81, '12:20 PM', '7:44 PM', 'Praesent id massa id nisl venenatis lacinia.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (107, 96, '2:28 PM', '7:48 PM', 'Ut at dolor quis odio consequat varius.', 8);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (108, 81, '12:27 PM', '6:16 PM', 'Quisque id justo sit amet sapien dignissim vestibulum.', 3);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (109, 67, '2:40 PM', '7:37 PM', 'Aenean lectus.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (110, 73, '12:28 PM', '6:07 PM', 'Nulla tellus.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (111, 59, '2:40 PM', '6:58 PM', 'Integer tincidunt ante vel ipsum.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (112, 62, '2:51 PM', '7:55 PM', 'Praesent id massa id nisl venenatis lacinia.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (113, 85, '12:40 PM', '7:29 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 28);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (114, 55, '2:04 PM', '6:53 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 25);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (115, 40, '12:36 PM', '7:42 PM', 'Donec posuere metus vitae ipsum.', 3);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (116, 85, '12:32 PM', '7:43 PM', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 29);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (117, 85, '1:13 PM', '7:48 PM', 'Aenean sit amet justo.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (118, 61, '2:09 PM', '6:06 PM', 'Nulla tempus.', 39);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (119, 77, '12:43 PM', '7:32 PM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (120, 64, '2:47 PM', '6:40 PM', 'Vivamus vel nulla eget eros elementum pellentesque.', 40);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (121, 68, '1:57 PM', '7:46 PM', 'Sed sagittis.', 31);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (122, 40, '12:32 PM', '6:09 PM', 'Nulla mollis molestie lorem.', 33);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (123, 49, '1:22 PM', '7:25 PM', 'Praesent blandit lacinia erat.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (124, 51, '2:51 PM', '6:07 PM', 'In blandit ultrices enim.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (125, 54, '2:28 PM', '6:20 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (126, 46, '2:23 PM', '7:44 PM', 'Nulla facilisi.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (127, 41, '2:05 PM', '6:54 PM', 'Praesent id massa id nisl venenatis lacinia.', 40);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (128, 63, '2:36 PM', '7:45 PM', 'Proin risus.', 40);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (129, 67, '1:25 PM', '7:04 PM', 'Aliquam erat volutpat.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (130, 49, '2:20 PM', '7:58 PM', 'Curabitur at ipsum ac tellus semper interdum.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (131, 96, '1:22 PM', '6:59 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (132, 93, '2:19 PM', '7:49 PM', 'Fusce consequat.', 31);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (133, 48, '12:39 PM', '7:18 PM', 'Integer non velit.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (134, 98, '2:20 PM', '6:13 PM', 'Morbi porttitor lorem id ligula.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (135, 62, '2:30 PM', '6:54 PM', 'Aliquam non mauris.', 32);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (136, 69, '12:29 PM', '7:07 PM', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (137, 86, '12:25 PM', '7:32 PM', 'Suspendisse ornare consequat lectus.', 15);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (138, 85, '12:54 PM', '6:40 PM', 'Integer tincidunt ante vel ipsum.', 9);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (139, 58, '2:31 PM', '7:47 PM', 'Morbi vel lectus in quam fringilla rhoncus.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (140, 51, '12:14 PM', '7:14 PM', 'Vivamus vel nulla eget eros elementum pellentesque.', 32);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (141, 50, '12:43 PM', '7:35 PM', 'Nulla facilisi.', 6);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (142, 80, '2:43 PM', '7:34 PM', 'Sed vel enim sit amet nunc viverra dapibus.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (143, 86, '1:57 PM', '6:51 PM', 'Vestibulum rutrum rutrum neque.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (144, 73, '1:02 PM', '6:54 PM', 'Nulla mollis molestie lorem.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (145, 48, '12:24 PM', '7:36 PM', 'Pellentesque at nulla.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (146, 62, '2:52 PM', '6:12 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (147, 71, '1:37 PM', '6:05 PM', 'Nam tristique tortor eu pede.', 12);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (148, 94, '1:04 PM', '6:13 PM', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 27);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (149, 99, '2:24 PM', '7:34 PM', 'Nulla tempus.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (150, 67, '1:36 PM', '6:44 PM', 'Duis at velit eu est congue elementum.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (151, 51, '1:22 PM', '6:16 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (152, 93, '1:04 PM', '7:58 PM', 'In blandit ultrices enim.', 7);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (153, 91, '1:27 PM', '7:11 PM', 'Nam nulla.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (154, 43, '12:01 PM', '6:32 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 32);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (155, 95, '1:56 PM', '6:02 PM', 'Praesent blandit lacinia erat.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (156, 55, '2:41 PM', '7:48 PM', 'In quis justo.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (157, 43, '2:33 PM', '7:09 PM', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (158, 71, '2:10 PM', '7:05 PM', 'In hac habitasse platea dictumst.', 3);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (159, 96, '2:31 PM', '7:29 PM', 'In hac habitasse platea dictumst.', 3);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (160, 42, '1:57 PM', '6:01 PM', 'Duis consequat dui nec nisi volutpat eleifend.', 25);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (161, 61, '12:29 PM', '7:25 PM', 'Praesent blandit lacinia erat.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (162, 98, '2:27 PM', '6:26 PM', 'Vivamus vestibulum sagittis sapien.', 38);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (163, 99, '1:28 PM', '7:56 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (164, 57, '2:31 PM', '7:12 PM', 'Suspendisse potenti.', 26);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (165, 85, '12:12 PM', '7:23 PM', 'Quisque porta volutpat erat.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (166, 73, '2:39 PM', '6:14 PM', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 39);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (167, 89, '12:10 PM', '7:25 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (168, 59, '2:26 PM', '7:25 PM', 'Aliquam erat volutpat.', 35);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (169, 93, '1:06 PM', '7:11 PM', 'Sed vel enim sit amet nunc viverra dapibus.', 1);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (170, 55, '2:33 PM', '7:35 PM', 'Donec ut mauris eget massa tempor convallis.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (171, 71, '2:16 PM', '6:59 PM', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 5);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (172, 41, '2:09 PM', '7:51 PM', 'Pellentesque at nulla.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (173, 87, '1:10 PM', '6:57 PM', 'Nam dui.', 26);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (174, 95, '12:02 PM', '6:50 PM', 'Morbi porttitor lorem id ligula.', 2);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (175, 56, '1:34 PM', '7:24 PM', 'Donec dapibus.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (176, 100, '1:33 PM', '6:16 PM', 'Etiam justo.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (177, 81, '2:28 PM', '7:42 PM', 'Sed ante.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (178, 86, '1:59 PM', '7:04 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (179, 44, '2:08 PM', '6:29 PM', 'Nullam molestie nibh in lectus.', 16);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (180, 63, '2:04 PM', '6:05 PM', 'Ut at dolor quis odio consequat varius.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (181, 67, '12:16 PM', '6:30 PM', 'Donec ut mauris eget massa tempor convallis.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (182, 67, '1:48 PM', '6:58 PM', 'Integer tincidunt ante vel ipsum.', 17);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (183, 83, '1:52 PM', '6:14 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (184, 98, '2:07 PM', '7:16 PM', 'Nulla justo.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (185, 77, '1:14 PM', '6:38 PM', 'Nulla facilisi.', 4);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (186, 43, '12:11 PM', '6:14 PM', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 10);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (187, 74, '1:10 PM', '6:43 PM', 'Proin eu mi.', 31);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (188, 60, '12:32 PM', '7:02 PM', 'Aenean auctor gravida sem.', 18);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (189, 87, '2:15 PM', '7:44 PM', 'Integer non velit.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (190, 69, '12:30 PM', '7:06 PM', 'Aenean lectus.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (191, 62, '2:49 PM', '7:53 PM', 'Nulla tempus.', 28);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (192, 57, '12:28 PM', '7:41 PM', 'Integer ac leo.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (193, 53, '2:52 PM', '6:23 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 20);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (194, 58, '1:58 PM', '6:44 PM', 'In eleifend quam a odio.', 38);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (195, 48, '2:14 PM', '6:27 PM', 'Quisque porta volutpat erat.', 1);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (196, 85, '12:50 PM', '6:59 PM', 'Morbi vel lectus in quam fringilla rhoncus.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (197, 60, '12:38 PM', '6:59 PM', 'Curabitur gravida nisi at nibh.', 21);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (198, 92, '1:53 PM', '6:39 PM', 'Mauris ullamcorper purus sit amet nulla.', 37);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (199, 71, '12:07 PM', '7:21 PM', 'Donec semper sapien a libero.', 28);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (200, 84, '2:10 PM', '7:28 PM', 'Quisque ut erat.', 11);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (201, 68, '12:55 PM', '6:42 PM', 'Duis ac nibh.', 33);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (202, 51, '12:53 PM', '7:51 PM', 'Quisque id justo sit amet sapien dignissim vestibulum.', 40);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (203, 64, '1:20 PM', '6:32 PM', 'Integer ac neque.', 14);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (204, 86, '1:22 PM', '6:44 PM', 'Morbi ut odio.', 23);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (205, 96, '2:01 PM', '7:55 PM', 'Duis consequat dui nec nisi volutpat eleifend.', 24);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (206, 78, '12:32 PM', '6:54 PM', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (207, 92, '1:12 PM', '7:35 PM', 'Pellentesque eget nunc.', 30);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (208, 83, '2:08 PM', '7:38 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 13);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (209, 95, '2:29 PM', '7:00 PM', 'Proin risus.', 22);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (210, 73, '1:27 PM', '7:56 PM', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 39);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (211, 94, '12:25 PM', '6:33 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 36);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (212, 76, '2:31 PM', '7:03 PM', 'Nullam varius.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (213, 42, '2:28 PM', '7:45 PM', 'Duis consequat dui nec nisi volutpat eleifend.', 19);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (214, 58, '2:58 PM', '7:33 PM', 'Donec quis orci eget orci vehicula condimentum.', 34);
insert into A_ESPACIO (ID, CAPACIDAD_ORIGINAL, HORA_APERTURA, HORA_CIERRE, DESCRIPCION, NUM_VISITANTES) values (215, 59, '1:37 PM', '6:37 PM', 'Nunc purus.', 27);
