insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (16, 3117, '8:02 AM', '8:54 PM', 'Nullam porttitor lacus at turpis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (17, 5786, '8:06 AM', '8:32 PM', 'Nullam varius.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (18, 3149, '8:37 AM', '8:54 PM', 'Curabitur at ipsum ac tellus semper interdum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (19, 4776, '8:52 AM', '8:42 PM', 'Aenean auctor gravida sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (20, 3158, '8:26 AM', '8:35 PM', 'Nulla mollis molestie lorem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (21, 4181, '8:43 AM', '8:39 PM', 'Nullam porttitor lacus at turpis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (22, 4059, '8:06 AM', '8:31 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (23, 5854, '8:54 AM', '8:41 PM', 'Duis at velit eu est congue elementum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (24, 3987, '8:41 AM', '8:32 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (25, 5373, '8:15 AM', '8:48 PM', 'Pellentesque at nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (26, 5442, '8:47 AM', '8:53 PM', 'Duis aliquam convallis nunc.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (27, 4037, '8:01 AM', '8:57 PM', 'Donec posuere metus vitae ipsum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (28, 4341, '8:33 AM', '8:32 PM', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (29, 4954, '8:00 AM', '8:51 PM', 'Donec semper sapien a libero.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (30, 4304, '8:13 AM', '8:39 PM', 'In hac habitasse platea dictumst.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (31, 5635, '8:33 AM', '8:39 PM', 'Fusce consequat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (32, 4620, '8:29 AM', '8:50 PM', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (33, 3166, '8:38 AM', '8:36 PM', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (34, 4817, '8:47 AM', '8:49 PM', 'Praesent blandit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (35, 3216, '8:10 AM', '8:32 PM', 'Pellentesque ultrices mattis odio.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (36, 5732, '8:10 AM', '8:53 PM', 'Phasellus id sapien in sapien iaculis congue.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (37, 4257, '8:30 AM', '8:38 PM', 'Donec quis orci eget orci vehicula condimentum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (38, 3583, '8:51 AM', '8:37 PM', 'Curabitur gravida nisi at nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (39, 5270, '8:38 AM', '8:30 PM', 'Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (40, 3013, '8:14 AM', '8:39 PM', 'Donec vitae nisi.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (41, 3911, '8:30 AM', '8:36 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (42, 5028, '8:15 AM', '8:34 PM', 'Morbi ut odio.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (43, 3279, '8:42 AM', '8:34 PM', 'Cras non velit nec nisi vulputate nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (44, 3986, '8:18 AM', '8:52 PM', 'Phasellus sit amet erat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (45, 4579, '8:17 AM', '8:55 PM', 'Nulla tempus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (46, 4533, '8:32 AM', '8:55 PM', 'Nulla suscipit ligula in lacus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (47, 4603, '8:19 AM', '8:56 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (48, 3270, '8:40 AM', '8:51 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (49, 3186, '8:59 AM', '8:35 PM', 'Proin at turpis a pede posuere nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (50, 4939, '8:03 AM', '8:39 PM', 'Donec semper sapien a libero.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (51, 3172, '8:47 AM', '8:38 PM', 'Suspendisse potenti.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (52, 4160, '8:55 AM', '8:50 PM', 'Fusce consequat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (53, 4315, '8:12 AM', '8:51 PM', 'Pellentesque at nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (54, 4656, '8:07 AM', '8:55 PM', 'Integer a nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (55, 3347, '8:29 AM', '8:56 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (56, 3541, '8:45 AM', '8:37 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (57, 3585, '8:44 AM', '8:49 PM', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (58, 5400, '8:35 AM', '8:38 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (59, 5144, '8:36 AM', '8:42 PM', 'Praesent blandit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (60, 3351, '8:33 AM', '8:51 PM', 'Cras pellentesque volutpat dui.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (61, 4361, '8:18 AM', '8:51 PM', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (62, 5067, '8:05 AM', '8:43 PM', 'Vivamus vel nulla eget eros elementum pellentesque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (63, 5426, '8:48 AM', '8:43 PM', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (64, 5671, '8:49 AM', '8:59 PM', 'Morbi non lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (65, 3571, '8:37 AM', '8:51 PM', 'Etiam pretium iaculis justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (66, 5341, '8:16 AM', '8:39 PM', 'Aliquam non mauris.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (67, 4321, '8:26 AM', '8:40 PM', 'Nulla ut erat id mauris vulputate elementum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (68, 4774, '8:12 AM', '8:53 PM', 'Nullam molestie nibh in lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (69, 5258, '8:16 AM', '8:59 PM', 'In quis justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (70, 5865, '8:42 AM', '8:58 PM', 'Nulla justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (71, 5036, '8:08 AM', '8:30 PM', 'Aenean auctor gravida sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (72, 5663, '8:24 AM', '8:37 PM', 'Duis bibendum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (73, 4408, '8:39 AM', '8:44 PM', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (74, 3199, '8:33 AM', '8:54 PM', 'Mauris lacinia sapien quis libero.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (75, 5774, '8:34 AM', '8:37 PM', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (76, 4865, '8:15 AM', '8:41 PM', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (77, 3076, '8:31 AM', '8:59 PM', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (78, 3633, '8:37 AM', '8:43 PM', 'Proin at turpis a pede posuere nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (79, 5877, '8:05 AM', '8:58 PM', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (80, 3199, '8:14 AM', '8:31 PM', 'Morbi non lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (81, 4456, '8:21 AM', '8:52 PM', 'Maecenas tincidunt lacus at velit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (82, 5883, '8:30 AM', '8:37 PM', 'Etiam vel augue.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (83, 3674, '8:55 AM', '8:42 PM', 'Praesent id massa id nisl venenatis lacinia.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (84, 4181, '8:11 AM', '8:55 PM', 'Cras pellentesque volutpat dui.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (85, 3685, '8:09 AM', '8:35 PM', 'Maecenas ut massa quis augue luctus tincidunt.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (86, 5327, '8:48 AM', '8:52 PM', 'Nulla suscipit ligula in lacus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (87, 4779, '8:45 AM', '8:57 PM', 'Praesent lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (88, 3871, '8:18 AM', '8:52 PM', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (89, 5514, '8:19 AM', '8:55 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (90, 4366, '8:31 AM', '8:49 PM', 'Vivamus vestibulum sagittis sapien.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (91, 5539, '8:12 AM', '8:30 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (92, 5664, '8:50 AM', '8:52 PM', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (93, 5125, '8:55 AM', '8:53 PM', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (94, 3242, '8:25 AM', '8:33 PM', 'Morbi non lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (95, 4374, '8:36 AM', '8:37 PM', 'Donec dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (96, 5308, '8:24 AM', '8:59 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (97, 5565, '8:31 AM', '8:42 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (98, 3654, '8:42 AM', '8:48 PM', 'Pellentesque viverra pede ac diam.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (99, 3782, '8:10 AM', '8:52 PM', 'Maecenas pulvinar lobortis est.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (100, 5922, '8:43 AM', '8:37 PM', 'Cras non velit nec nisi vulputate nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (101, 5460, '8:24 AM', '8:47 PM', 'Nunc rhoncus dui vel sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (102, 3886, '8:12 AM', '8:50 PM', 'Ut at dolor quis odio consequat varius.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (103, 3763, '8:46 AM', '8:37 PM', 'Donec ut mauris eget massa tempor convallis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (104, 4524, '8:47 AM', '8:57 PM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (105, 5070, '8:35 AM', '8:37 PM', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (106, 5376, '8:24 AM', '8:46 PM', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (107, 4955, '8:33 AM', '8:55 PM', 'Sed vel enim sit amet nunc viverra dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (108, 5952, '8:53 AM', '8:37 PM', 'Donec dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (109, 3662, '8:43 AM', '8:44 PM', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (110, 4290, '8:14 AM', '8:45 PM', 'Sed vel enim sit amet nunc viverra dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (111, 4331, '8:12 AM', '8:52 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (112, 3875, '8:38 AM', '8:57 PM', 'Curabitur at ipsum ac tellus semper interdum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (113, 5267, '8:20 AM', '8:54 PM', 'Vivamus tortor.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (114, 3066, '8:11 AM', '8:57 PM', 'Proin at turpis a pede posuere nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (115, 4278, '8:40 AM', '8:41 PM', 'Quisque id justo sit amet sapien dignissim vestibulum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (116, 4539, '8:10 AM', '8:36 PM', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (117, 4019, '8:09 AM', '8:46 PM', 'Proin at turpis a pede posuere nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (118, 4958, '8:56 AM', '8:31 PM', 'Ut at dolor quis odio consequat varius.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (119, 3042, '8:00 AM', '8:54 PM', 'Sed ante.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (120, 3719, '8:23 AM', '8:52 PM', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (121, 4046, '8:20 AM', '8:43 PM', 'Nulla suscipit ligula in lacus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (122, 4660, '8:37 AM', '8:30 PM', 'Morbi porttitor lorem id ligula.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (123, 5485, '8:27 AM', '8:37 PM', 'Duis aliquam convallis nunc.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (124, 4177, '8:09 AM', '8:59 PM', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (125, 5821, '8:24 AM', '8:36 PM', 'Donec dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (126, 3533, '8:49 AM', '8:37 PM', 'Maecenas pulvinar lobortis est.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (127, 4218, '8:43 AM', '8:34 PM', 'Integer non velit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (128, 3466, '8:33 AM', '8:58 PM', 'Suspendisse accumsan tortor quis turpis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (129, 3186, '8:47 AM', '8:31 PM', 'In sagittis dui vel nisl.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (130, 4485, '8:09 AM', '8:59 PM', 'Proin eu mi.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (131, 5515, '8:59 AM', '8:37 PM', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (132, 3601, '8:11 AM', '8:45 PM', 'Proin eu mi.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (133, 3737, '8:07 AM', '8:59 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (134, 5319, '8:03 AM', '8:38 PM', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (135, 5596, '8:13 AM', '8:31 PM', 'Integer non velit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (136, 3596, '8:42 AM', '8:34 PM', 'Aenean sit amet justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (137, 5950, '8:27 AM', '8:41 PM', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (138, 3814, '8:22 AM', '8:31 PM', 'Nullam porttitor lacus at turpis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (139, 4963, '8:59 AM', '8:49 PM', 'Suspendisse ornare consequat lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (140, 4973, '8:02 AM', '8:57 PM', 'Sed accumsan felis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (141, 4903, '8:54 AM', '8:34 PM', 'Nullam molestie nibh in lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (142, 3625, '8:39 AM', '8:55 PM', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (143, 4932, '8:58 AM', '8:58 PM', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (144, 5943, '8:46 AM', '8:50 PM', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (145, 3063, '8:46 AM', '8:54 PM', 'In sagittis dui vel nisl.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (146, 4197, '8:33 AM', '8:48 PM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (147, 5067, '8:06 AM', '8:55 PM', 'Praesent blandit lacinia erat.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (148, 3354, '8:20 AM', '8:51 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (149, 3358, '8:38 AM', '8:30 PM', 'Nulla suscipit ligula in lacus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (150, 5113, '8:38 AM', '8:35 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (151, 4154, '8:47 AM', '8:52 PM', 'Sed vel enim sit amet nunc viverra dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (152, 5613, '8:37 AM', '8:57 PM', 'Donec ut dolor.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (153, 3623, '8:18 AM', '8:32 PM', 'Praesent blandit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (154, 5304, '8:27 AM', '8:30 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (155, 4602, '8:26 AM', '8:47 PM', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (156, 4112, '8:02 AM', '8:44 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (157, 5282, '8:12 AM', '8:50 PM', 'Aliquam quis turpis eget elit sodales scelerisque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (158, 4392, '8:58 AM', '8:31 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (159, 5498, '8:11 AM', '8:39 PM', 'Proin at turpis a pede posuere nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (160, 4071, '8:49 AM', '8:42 PM', 'Mauris lacinia sapien quis libero.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (161, 4610, '8:20 AM', '8:54 PM', 'Cras in purus eu magna vulputate luctus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (162, 3453, '8:23 AM', '8:41 PM', 'Donec semper sapien a libero.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (163, 5838, '8:43 AM', '8:33 PM', 'Nulla suscipit ligula in lacus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (164, 4207, '8:56 AM', '8:59 PM', 'Cras non velit nec nisi vulputate nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (165, 4197, '8:03 AM', '8:56 PM', 'Curabitur gravida nisi at nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (166, 4160, '8:15 AM', '8:41 PM', 'Curabitur gravida nisi at nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (167, 5600, '8:43 AM', '8:58 PM', 'Donec dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (168, 3337, '8:44 AM', '8:40 PM', 'Mauris ullamcorper purus sit amet nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (169, 5198, '8:22 AM', '8:32 PM', 'Duis consequat dui nec nisi volutpat eleifend.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (170, 4060, '8:23 AM', '8:52 PM', 'Nunc rhoncus dui vel sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (171, 5592, '8:32 AM', '8:50 PM', 'Suspendisse potenti.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (172, 4822, '8:33 AM', '8:52 PM', 'Pellentesque eget nunc.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (173, 5801, '8:43 AM', '8:51 PM', 'Nulla tempus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (174, 3970, '8:41 AM', '8:42 PM', 'Nunc rhoncus dui vel sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (175, 5607, '8:06 AM', '8:30 PM', 'Donec dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (176, 4779, '8:27 AM', '8:36 PM', 'Integer tincidunt ante vel ipsum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (177, 5324, '8:42 AM', '8:37 PM', 'Nullam molestie nibh in lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (178, 4393, '8:16 AM', '8:32 PM', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (179, 5934, '8:06 AM', '8:44 PM', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (180, 3787, '8:16 AM', '8:56 PM', 'Aenean lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (181, 3420, '8:57 AM', '8:57 PM', 'Etiam justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (182, 5818, '8:24 AM', '8:34 PM', 'Praesent blandit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (183, 3039, '8:05 AM', '8:54 PM', 'Suspendisse accumsan tortor quis turpis.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (184, 3914, '8:04 AM', '8:46 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (185, 4868, '8:42 AM', '8:45 PM', 'Maecenas ut massa quis augue luctus tincidunt.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (186, 3596, '8:21 AM', '8:41 PM', 'Sed ante.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (187, 5431, '8:10 AM', '8:34 PM', 'Duis ac nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (188, 5811, '8:42 AM', '8:34 PM', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (189, 3681, '8:16 AM', '8:45 PM', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (190, 4760, '8:01 AM', '8:36 PM', 'Donec ut dolor.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (191, 3235, '8:29 AM', '8:36 PM', 'Cras non velit nec nisi vulputate nonummy.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (192, 4706, '8:24 AM', '8:34 PM', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (193, 3710, '8:21 AM', '8:40 PM', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (194, 3089, '8:29 AM', '8:58 PM', 'Integer a nibh.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (195, 4512, '8:51 AM', '8:50 PM', 'Donec dapibus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (196, 5660, '8:51 AM', '8:47 PM', 'Integer non velit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (197, 4925, '8:17 AM', '8:40 PM', 'Donec vitae nisi.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (198, 3201, '8:16 AM', '8:50 PM', 'Maecenas pulvinar lobortis est.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (199, 3086, '8:51 AM', '8:55 PM', 'Integer ac neque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (200, 5482, '8:18 AM', '8:35 PM', 'Quisque id justo sit amet sapien dignissim vestibulum.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (201, 5358, '8:41 AM', '8:58 PM', 'Etiam faucibus cursus urna.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (202, 5138, '8:22 AM', '8:57 PM', 'Nam nulla.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (203, 5705, '8:04 AM', '8:30 PM', 'Integer ac neque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (204, 4064, '8:23 AM', '8:33 PM', 'Morbi quis tortor id nulla ultrices aliquet.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (205, 5596, '8:31 AM', '8:52 PM', 'Etiam justo.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (206, 4344, '8:55 AM', '8:47 PM', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (207, 3569, '8:21 AM', '8:35 PM', 'Vestibulum rutrum rutrum neque.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (208, 4611, '8:02 AM', '8:37 PM', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (209, 4666, '8:57 AM', '8:47 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (210, 5695, '8:57 AM', '8:34 PM', 'Donec ut dolor.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (211, 3777, '8:05 AM', '8:47 PM', 'Suspendisse potenti.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (212, 3077, '8:34 AM', '8:43 PM', 'Aliquam sit amet diam in magna bibendum imperdiet.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (213, 4406, '8:35 AM', '8:42 PM', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (214, 5471, '8:22 AM', '8:47 PM', 'Suspendisse ornare consequat lectus.', 1);
insert into A_ESPACIO (id, capacidad_original, hora_apertura, hora_cierre, descripcion, tipo_lugar) values (215, 3316, '8:23 AM', '8:40 PM', 'Praesent blandit.', 1);
