--AUTHOR: C.10 (DE.ZAMBRANO,AF.RINCON) PTO 2  
WITH CIUDAD AS(SELECT BEBIDAS.id, BEBIDAS.nombre, BEBIDAS.grado_alcohol, BARES.ciudad, count (*) AS NUMERO_BARES_QUE_SIRVEN
FROM PARRANDEROS.bares, PARRANDEROS.sirven, PARRANDEROS.bebidas
WHERE BEBIDAS.id = SIRVEN.id_bebida 
GROUP BY BEBIDAS.id,BARES.ciudad, BEBIDAS.nombre, BEBIDAS.grado_alcohol),

MASDE10 AS(SELECT GUSTAN.id_bebida, COUNT(*) AS BEBEDORES_QUE_LA_TOMAN
FROM PARRANDEROS.gustan
GROUP BY GUSTAN.id_bebida
HAVING count(*)>=10)

SELECT CIUDAD.id, CIUDAD.nombre, CIUDAD.grado_alcohol, CIUDAD.ciudad, CIUDAD.NUMERO_BARES_QUE_SIRVEN
FROM CIUDAD INNER JOIN MASDE10
ON CIUDAD.id = MASDE10.id_bebida
ORDER BY CIUDAD.nombre ASC, CIUDAD.ciudad ASC, CIUDAD.NUMERO_BARES_QUE_SIRVEN ASC;