--AUTHOR: C.10 (DE.ZAMBRANO,AF.RINCON) PTO 4
SELECT BEBEDORES.ciudad,BEBEDORES.nombre,GUSTAN.id_bebedor AS IDBEBEDOR, count(BEBIDAS.nombre) AS NUMERO_BEBIDAS 
FROM PARRANDEROS.bebidas, PARRANDEROS.gustan, PARRANDEROS.bebedores
WHERE BEBIDAS.id = GUSTAN.id_bebida AND BEBEDORES.id = GUSTAN.id_bebedor AND BEBIDAS.grado_alcohol > 10  AND BEBEDORES.presupuesto = 'Alto'
GROUP BY BEBEDORES.ciudad,BEBEDORES.nombre,GUSTAN.id_bebedor
HAVING count(BEBIDAS.nombre) BETWEEN 5 AND 10
ORDER BY BEBEDORES.ciudad ASC,BEBEDORES.nombre ASC, NUMERO_BEBIDAS ASC