CREATE TABLE BOSS
(
     IDENTIFICACION VARCHAR(50),
     CORREO VARCHAR(70),
     NOMBRE VARCHAR(40) NOT NULL,
     TYPE_DIRECTION VARCHAR(30),
     AREA NUMBER
     CONSTRAINT PK_IDENTIFICACION PRIMARY KEY (IDENTIFICACION);
)

ALTER TABLE BOSS
ADD CONSTRAINT FK_AREA 
FOREIGN KEY (AREA) REFERENCES DIRECTION(ID);
ENABLE;

ALTER TABLE BOSS
ADD CONSTRAINT ND_CORREO 
UNIQUE (CORREO);
ENABLE;

ALTER TABLE BOSS
ADD CONSTRAINT CK_TYPE_DIRECTION
CHECK (TYPE_DIRECTION IN ('ADMINISTRATIVE','TECH', 'JURIDIC'));
ENABLE;


CREATE TABLE BARES(
    CODIGO NUMBER,
    NOMBRE VARCHAR(20) NOT NULL,
    CIUDAD VARCHAR(30) NOT NULL,
    PRESUPUESTO VARCHAR(30) NOT NULL,
    CANT_SEDES NUMBER
    CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO)
)
ALTER TABLE BARES
ADD CONSTRAINT CK_PRESUPUESTO
CHECK (PRESUPUESTO IN ('Alto','Bajo','medio'))
enable;
ALTER TABLE BARES
ADD CONSTRAINT CK_CANT_SEDES
CHECK (CANT_SEDES > 0)
enable; 

CREATE TABLE FRECUENTAN(
    ID_BAR NUMBER,
    ID_BEBEDOR NUMBER,
    HORARIO VARCHAR(70),
    ULTIMA_VISITA DATE
    CONSTRAINT PK_FRECUENTAN PRIMARY KEY (ID_BAR,ID_BEBDOR,HORARIO,ULTIMA_VISITA)
)

ALTER TABLE FRECUENTAN
ADD CONSTRAINT FK_ID_BAR
FOREIGN KEY (ID_BAR) REFERENCES BARES(ID)
ENABLE;

ALTER TABLE FRECUENTAN
ADD CONSTRAINT FK_ID_BEBEDOR
FOREIGN KEY (ID_BEBEDOR) REFERENCES BEBEDORES(ID)
ENABLE;

ALTER TABLE BARES
ADD CONSTRAINT CK_HORARIO
CHECK (HORARIO IN ('diurno','nocturno','todos'))
enable;

Select PARRANDEROS.BEBEDORES.NOMBRE,t3.id,COUNT(PARRANDEROS.BEBEDORES.id)
from
(   
    SELECT t1.id
    from (
        SELECT parranderos.bebidas.id,parranderos.bebidas.grado_alcohol
        FROM PARRANDEROS.BEBIDAS
    )t1
    minus
    Select t2.id
    from (
        select parranderos.bebidas.id,parranderos.bebidas.grado_alcohol
        from parranderos.bebidas
        where bebidas.grado_alcohol = 0
    )t2
)t3,parranderos.gustan,parranderos.bebedores
GROUP BY PARRANDEROS.BEBEDORES.NOMBRE,t3.id
ORDER BY COUNT(PARRANDEROS.BEBEDORES.ID) DESC;













