SELECT tcols.NOMBRE_TABLA,tcols.COLUMN_NAME AS NOMBRE_COLUMNA,tcols.TIPO_DATO  
FROM (SELECT TABLE_NAME AS NOMBRE_TABLA,DATA_TYPE AS TIPO_DATO, COLUMN_NAME
      FROM ALL_TAB_COLUMNS
      WHERE OWNER = 'PARRANDEROS')tcols, 
     (SELECT TABLE_NAME AS NOMBRE_TABLA, CONSTRAINT_NAME, COLUMN_NAME
      FROM ALL_CONS_COLUMNS
      WHERE OWNER = 'PARRANDEROS'
      AND CONSTRAINT_NAME LIKE 'PK%_')tpks 
WHERE tcols.COLUMN_NAME = tpks.COLUMN_NAME
AND tcols.NOMBRE_TABLA= tpks.NOMBRE_TABLA
ORDER BY tcols.NOMBRE_TABLA ASC, tcols.COLUMN_NAME ASC;