SELECT tfinal2.NOMBRE_TABLA,tfinal2.NOMBRE_COLUMNA,tfinal2.TIPO_DATO,COALESCE(tfinal2.NOMBRE_RESTRICCION,'NO TIENE') AS NOMBRE_RESTRICCION,tfinal2.PERMITE_NULOS
FROM(SELECT tcols.NOMBRE_COLUMNA, tcols.NOMBRE_TABLA,tcols.TIPO_DATO,tcons.NOMBRE_RESTRICCION,tcols.PERMITE_NULOS
    FROM (SELECT COLUMN_NAME AS NOMBRE_COLUMNA, TABLE_NAME AS NOMBRE_TABLA, DATA_TYPE AS TIPO_DATO,NULLABLE AS PERMITE_NULOS
          FROM ALL_TAB_COLUMNS
          WHERE OWNER = 'PARRANDEROS')tcols 
          FULL OUTER JOIN 
         (SELECT COLUMN_NAME AS NOMBRE_COLUMNA, TABLE_NAME AS NOMBRE_TABLA, CONSTRAINT_NAME AS NOMBRE_RESTRICCION
          FROM ALL_CONS_COLUMNS
          WHERE OWNER = 'PARRANDEROS')tcons 
          ON tcols.NOMBRE_COLUMNA = tcons.NOMBRE_COLUMNA)tfinal2 
ORDER BY tfinal2.NOMBRE_TABLA ASC,tfinal2.NOMBRE_COLUMNA ASC,tfinal2.NOMBRE_RESTRICCION ASC;