SELECT TABLE_NAME AS NOMBRE_TABLA,DATA_TYPE AS TIPO_DATO,COUNT(*) AS NUM_COLUMNAS_XTIPO,AVG(AVG_COL_LEN) AS PROMEDIO_LONGITUD_COL
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'PARRANDEROS'
GROUP BY TABLE_NAME,DATA_TYPE
ORDER BY TABLE_NAME ASC, DATA_TYPE ASC,COUNT(*) ASC;  