SPOOL C:\Users\PATH(CAMBIAR)\script_Pto5_b.sql
SELECT 'SELECT TQUERY.NOMBRE_COLUMNA,TQUERY.NOMBRE_TABLA,TQUERY.NUM_RESTRICCIONES_XCOL FROM(SELECT * FROM ( SELECT COLUMN_NAME AS NOMBRE_COLUMNA, TABLE_NAME AS NOMBRE_TABLA FROM ALL_TAB_COLUMNS WHERE OWNER = ''PARRANDEROS'') TCOL LEFT JOIN (SELECT COLUMN_NAME, TABLE_NAME,COUNT(CONSTRAINT_NAME)AS NUM_RESTRICCIONES_XCOL FROM ALL_CONS_COLUMNS WHERE OWNER = ''PARRANDEROS'' GROUP BY COLUMN_NAME,TABLE_NAME)TCONS ON TCOL.NOMBRE_COLUMNA = TCONS.COLUMN_NAME AND TCOL.NOMBRE_TABLA = TCONS.TABLE_NAME)TQUERY WHERE TQUERY.TABLE_NAME = '''||tcols.NOMBRE_TABLA||''' AND TQUERY.COLUMN_NAME = '''||tcols.NOMBRE_COLUMNA||''';' AS QUERY
        FROM (SELECT tfinal3.NOMBRE_COLUMNA,tfinal3.NOMBRE_TABLA, COALESCE(tfinal3.NUM_RESTRICCIONES_XCOL, 0) AS NUM_RESTRICCIONES_AFECTAN
              FROM    (SELECT tcols.NOMBRE_COLUMNA, tcols.NOMBRE_TABLA, tcons.NUM_RESTRICCIONES_XCOL
                       FROM (SELECT COLUMN_NAME AS NOMBRE_COLUMNA, TABLE_NAME AS NOMBRE_TABLA, LENGTH(COLUMN_NAME) AS longitud_cadena
                             FROM ALL_TAB_COLUMNS
                             WHERE OWNER = 'PARRANDEROS' 
                             AND LENGTH(COLUMN_NAME)>6)tcols 
                             LEFT JOIN 
                            (SELECT COLUMN_NAME AS NOMBRE_COLUMNA, TABLE_NAME AS NOMBRE_TABLA,COUNT(CONSTRAINT_NAME)AS NUM_RESTRICCIONES_XCOL
                             FROM ALL_CONS_COLUMNS
                             WHERE OWNER = 'PARRANDEROS'
                             GROUP BY COLUMN_NAME,TABLE_NAME)tcons 
                             ON  tcols.NOMBRE_COLUMNA = tcons.NOMBRE_COLUMNA 
                             AND tcols.NOMBRE_TABLA = tcons.NOMBRE_TABLA) tfinal3)tcols;
SPOOL OFF
@C:\Users\PATH(CAMBIAR)\script_Pto5_b.sql